pyproject.toml
Similar to https://github.com/apache/iceberg/pull/8647, I think we would need to exclude 2.4.0, 2.4.1 here on the overall project's dependencies. 
Given that pydantic has not de-shelved these faulty versions, we might not need to exclude them from the PyIceberg dependencies in order to prevent the dependency resolver from from installing pydantic 2.4.0 or 2.4.1
When pip installing pyiceberg 0.5.0 without version constraints, we see the following error on load_catalog function call:
```
KeyError                                  Traceback (most recent call last)
/tmp/ipykernel_252/2476882581.py in <cell line: 1>()
----> 1 from pyiceberg.catalog import load_catalog
2 
3 catalog = load_catalog("lacus")
/lib/python3.10/site-packages/pyiceberg/catalog/__init__.py in <module>
40 from …
```
=> pydantic exclude 2.4.0, 2.4.1

pyiceberg/catalog/rest.py, pyiceberg/table/__init__.py, tests/catalog/test_base.py, tests/test_integration.py
We were sending a table identifier before in `['accounting', 'tax', 'invoices']`, but it has to be `{'namespace': ['accounting, 'tax'], 'name': 'invoices'}` 😭
=> Fix the TableIdentifier

pyiceberg/io/pyarrow.py
I noticed that the FixedType was missing.
=> Convert the Logical to Physical map to a visitor

dev/provision.py, dev/spark-defaults.conf, pyiceberg/table/__init__.py, tests/test_integration.py
=> Add logic for table format-version updates

pyiceberg/avro/file.py, pyiceberg/avro/resolver.py, pyiceberg/avro/writer.py, pyiceberg/manifest.py, pyiceberg/schema.py, pyiceberg/types.py, tests/avro/test_decoder.py, tests/avro/test_file.py, tests/avro/test_reader.py, tests/avro/test_resolver.py, tests/test_integration_manifest.py, tests/test_types.py, tests/utils/test_manifest.py
For V1 and V2 there are some differences that are hard to enforce without this:
- `1: snapshot_id` is required for V1, optional for V2
- `105: block_size_in_bytes` needs to be written for V1, but omitted for V2 (this leverages the `write-default`).
- `3: sequence_number` and `4: file_sequence_number` can be omited for V1.
Everything that we read, we map it to V2. However, when writing we also want to be compliant with the V1 spec, and this is where the writer tree comes in since we construct a tree for V1 or V2.
=> Construct a writer tree

mkdocs/docs/api.md
* Rename column example in [this](https://py.iceberg.apache.org/api/#rename-column) doc is incorrect. 
* This PR updates the example to use `update.rename_column(...)` instead of `update.rename(...)`.
After PR
```
with table.update_schema() as update:
update.rename_column("retries", "num_retries")
update.rename_column("properties.confirmed_by", "exchange")
```
=> Fix column rename doc example to reflect correct API

pyiceberg/expressions/parser.py, tests/expressions/test_parser.py
Fixes #64 . If there are multiple and/or conditions currently, our expression parser will ignore anything after the second predicate. This change fixes the issue by forwarding the remaining predicates as the argument to `*rest: BooleanExpression` for And and Or.
=> Expression: Fix for when multiple and/or expressions are specified via string

pyiceberg/utils/schema_conversion.py, tests/avro/test_file.py
Fix #14 
This PR fixes incorrect schema conversion from Iceberg's Fixed, Decimal, and UUID to Avro's:
- Fixed and UUID: missing required field "name"
- Decimal: According to spec and the current avro writer implementation, decimal is written as a "fixed" type instead of "bytes"
=> Fix Iceberg to Avro Schema Conversion: Fixed, Decimal, UUID

pyiceberg/utils/config.py, tests/__init__.py, tests/catalog/test_rest.py, tests/utils/test_config.py
I found that I was unable to change a catalog URI after it had been configured by an environment variable. Example, 
```
import os
os.environ["PYICEBERG_CATALOG__SOMEDB__URI"] = "https://service-one.io"
from pyiceberg.catalog import load_catalog
catalog = load_catalog("somedb", uri="https://service-two.io")
```
[tries to connect to `https://service-one.io`]
I think the more intuitive behavior is that the URI would be initialized based on the environment variable (if present) but that the argument passed to `load_catalog` would be able to override the value. This PR updates the behavior so that the passed in argument takes precedence, by swapping the lhs and rhs preference in the `merge_config` method.
=> allow override env-variables in load_catalog

pyiceberg/table/__init__.py
We should only use this in the table module.
Follow up on https://github.com/apache/iceberg-python/pull/60#discussion_r1355656751
=> Make `next_sequence_number` private

pyiceberg/manifest.py, tests/avro/test_file.py, tests/test_integration_manifest.py
Spec id was removed in https://github.com/apache/iceberg-python/pull/40/files to wait for the decision of https://github.com/apache/iceberg/pull/8730. This PR adds it back and is needed to unblock issue https://github.com/apache/iceberg-python/issues/46
=> Add `spec_id` back to data file

.github/workflows/python-release.yml, mkdocs/docs/contributing.md, mkdocs/docs/how-to-release.md
This is not applicable anymore now Python has its own repository
=> Remove python working directory

.github/workflows/python-release.yml
When we test the binaries, we also fail on errors, which is more strict than in our regular CI
=> Don't fail on warning when releasing

pyiceberg/table/__init__.py
The `examples` is deprecated
```
E   pydantic.warnings.PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'example'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.4/migration/
```
=> Remove `example` since it is deprecated

mkdocs/docs/verify-release.md
This PR removes the additional `.asc` in the script for verifying checksums
=> Doc: Fix "Verifying Checksums" script in verify-release.md

dev/provision.py, pyiceberg/io/pyarrow.py, pyiceberg/schema.py, tests/io/test_pyarrow.py, tests/test_integration.py, tests/test_schema.py
We sanitized column name to meet the Avro restriction when writing parquet data (https://github.com/apache/iceberg/blob/ad602a379584512d1d96eda557c20cf2af21d1b2/core/src/main/java/org/apache/iceberg/avro/AvroSchemaUtil.java#L429).
This PR fix issues https://github.com/apache/iceberg-python/issues/81.
=> Make to_arrow function capable of handling parquet files with sanitized name due to Avro restirction

.pre-commit-config.yaml, pyiceberg/io/pyarrow.py, pyiceberg/schema.py, tests/test_schema.py
Replace old %-formatted by f-strings and add `flynt` hook to pre-commit to auto-detect and fix them.
=> Replace old `%-formatted` by `f-strings`

pyiceberg/table/__init__.py
It is not super clear from the current structure:
https://github.com/apache/iceberg/blob/main/open-api/rest-catalog-open-api.py#L304-L329
This is because I had to deconstruct the object. It would be great to get  https://github.com/apache/iceberg/pull/7710 in.
=> Fix the nullability of `snapshot-id` on `AssertRefSnapshotId`

mkdocs/docs/api.md
Fixes #78 
- Adds the `location` parameter to the `catalog.create_table(...)` example for more context.
- Adds the code to initialize the catalog in a database if this was not done previously
=> Api docs refactor

pyiceberg/io/pyarrow.py
=> Fixed typos

pyiceberg/table/__init__.py
I found a thread safety bug where some unwanted partitions would make it past the partition filter. I found and tested this fix on a simple Iceberg table with one schema spec, 5 manifest files (so 5 threads used in the thread pool), and thousands of partitions.
I've also solved this with a thread local storage approach to create fewer `_ExpressionEvaluator` instances under the hood, but I didn't think that'd be worth the additional complexity, especially with per-thread cleanup.
TODO
=> fix: partition evaluator thread safety

pyiceberg/avro/decoder.py, pyiceberg/avro/encoder.py, pyiceberg/catalog/rest.py, pyiceberg/conversions.py, pyiceberg/io/pyarrow.py, pyiceberg/serializers.py, pyiceberg/typedef.py, pyiceberg/utils/config.py, tests/catalog/test_hive.py, tests/conftest.py, tests/io/test_pyarrow.py, tests/table/test_metadata.py, tests/test_transforms.py, tests/utils/test_config.py
We wrapped a schema in a schema.
=> Refactor Arrow schema conversion

Makefile, pyiceberg/manifest.py, pyproject.toml, tests/catalog/test_sql.py, tests/conftest.py, tests/io/test_io.py, tests/io/test_pyarrow_stats.py, tests/test_integration.py, tests/utils/test_manifest.py
Migrated https://github.com/apache/iceberg/pull/6703/ to the new repository.
=> Catch warning in PyLint tests

.asf.yaml
`~` is not a valid path, updating this to `/`.
From https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features:
=> Fix Github Pages path

pyiceberg/cli/console.py, pyiceberg/cli/output.py, pyiceberg/table/__init__.py
Same as https://github.com/apache/iceberg/pull/8570, forgot to raise the PR here
=> Add list-refs cli command

pyiceberg/catalog/__init__.py, pyiceberg/catalog/dynamodb.py, pyiceberg/catalog/glue.py, pyiceberg/catalog/hive.py, pyiceberg/catalog/rest.py, pyiceberg/catalog/sql.py, tests/catalog/test_base.py, tests/catalog/test_dynamodb.py, tests/catalog/test_glue.py, tests/catalog/test_hive.py, tests/catalog/test_rest.py, tests/catalog/test_sql.py, tests/conftest.py
**Related Issue**: https://github.com/apache/iceberg-python/issues/123
**Validations Run**: 
`make test`
`make test-integration`
`make lint`
**Description**:
This PR fixes a bug where `Catalog` APIs returning a table (e.g. `catalog.load_table()`, `catalog.create_table()`, etc.) return a `Table` whose identifier has the catalog name prepended, but providing this identifier to catalog APIs to locate this table raises a `NoSuchTable` error due to the prepended catalog name.
This implementation simply removes the prepended catalog name from the identifier whenever it is composed of at least 3 elements and the catalog name matches the current catalog implementation in use. 
It currently only removes the catalog name in cases where a table identifier refers to the location of an existing table, …
=> Support catalog name in table identifier during load, rename, drop, and purge

pyiceberg/transforms.py, tests/test_transforms.py
This was a bad comparison due to comparing the truthy value of arbitrary objects. This failed in the case where `v` is equal to 0, as the truthy value of 0 is `False`. 
I have added a test that was failing before the change I made, and passes after the change was made.
Resolves #173
=> fix(bucket transform): bad comparison for truthy value

mkdocs/docs/api.md
=> feat(docs): example of multiple catalogs defined in .pyiceberg.yaml

pyiceberg/exceptions.py, pyiceberg/table/__init__.py, pyiceberg/table/refs.py, tests/table/test_init.py
This PR is the second part of #140 
It implements a `validate` method for each table requirement. This method raises a `CommitFailedException` with an appropriate error message if the table's metadata does not meet the requirements.
=> Table Requirements Validation

pyiceberg/table/__init__.py
When given the first snapshot-id of the table, the schema got should have schema_id = 0.
But under origin code's conditional statements, the use of walrus operator will cause the condition that when schema_id = 0, it will not pass the if statement, thus the schema will not change.
=> fix snapshot schema issue: wrong usage of walrus operator

pyiceberg/table/name_mapping.py, tests/table/test_name_mapping.py
All the things to (de)serialize the name-mapping, and all the neccessary visitors and such
=> Add name-mapping

poetry.lock, pyproject.toml, tests/catalog/test_dynamodb.py, tests/catalog/test_glue.py, tests/conftest.py
This is the PR relating to https://github.com/apache/iceberg-python/issues/222. 
This should be a drop in replacement for `moto.mock_s3`, by pointing the s3 clients at a moto server endpoint url. 
By doing this, you can:
1. Remove the patch to `aiobotocore`
2. Remove the requirement of using `pyiceberg.io.fsspec.FsspecFileIO` over the default of `pyiceberg.io.pyarrow.PyArrowFileIO`.
Glue and DynamoDB still use the basic `mock_glue` and `mock_dynamodb`. They could probably be moved over to the sever implementation as well, but it was taking more work than I wanted so I didn't include it.
=> Moto server implementation for pytest

dev/provision.py, pyiceberg/expressions/visitors.py, tests/test_integration.py
=> Allow filtering on newly added columns

pyiceberg/table/__init__.py
Resolves: [232](https://github.com/apache/iceberg-python/issues/232)
Python, certain values are considered False in a boolean context. These include None, 0, empty sequences/collections (`''`, `[]`, `{}`), and others. This is often referred to as “falsy” values.
With the current implementation of  ->    
```
def current_snapshot(self) -> Optional[Snapshot]
if snapshot_id := self.metadata.current_snapshot_id:
```
The walrus operator in the if condition will assign a value to snapshot_id, but it will marked as false in case of zero and None hence will skip snapshot_id = 0 as well, to solve this raise this PR
=> Bug fix falsy value of zero

pyiceberg/table/__init__.py, tests/table/test_init.py
When we alter the schema, we want to use the latest schema by default, except when you select a specific snapshot that has a schema-id.
=> Correct schema behavior

mkdocs/docs/configuration.md, pyiceberg/catalog/rest.py, tests/catalog/test_rest.py
Closes: https://github.com/apache/iceberg-python/issues/230
This PR introduces support for **Separation of Roles** in OAuth authorization when using the REST Catalog, by allowing the user to use a distinct Authorization Server to fetch the access token and use it against the REST Catalog. In this scenario, the responsibility of the REST Catalog lies in validating the access token, instead of taking their secrets and deducing their identity and authorization.
This will allow PyIceberg to re-authorize the client using the stored credentials against the appropriate auth server if AuthorizationExpiredError is detected (Refreshing access_token is out of scope of this PR)
=> Rest Catalog Support for a Separate OAuth Server URI

pyiceberg/catalog/sql.py, tests/catalog/test_sql.py
https://github.com/apache/iceberg-python/issues/262
This PR takes much code-spiration from @HonahX 's recent PR for a similar feature enhancement to the Glue Catalog.
The only difference here is that we use the **metadata_location** as the optimistic locking parameter to ensure that the version of the table we used to validate the requirements on is still the same when the SQL update is being made.
EDIT:
for methods that require rowcount on UPDATE and DELETE for optimistic locking, we now fallback to "SELECT ... FOR UPDATE" sqlalchemy expression [with_for_update](https://docs.sqlalchemy.org/en/20/core/selectable.html#sqlalchemy.sql.expression.CompoundSelect.with_for_update) to acquire a row level lock if the sqlalchemy dialect does not support rowcount for UPDATE / DELETE …
=> Add SqlCatalog _commit_table support

pyiceberg/transforms.py, tests/test_transforms.py
Currently, any falsey values will return None for their **TruncateTransform**. This results in **fill_parquet_file_metadata** throwing an exception whenever there is a falsey lower bound as the minimum value for the column statistic, as None cannot be encoded into "UTF-8" and fails for the function **to_bytes**.
The falsey values added in the test below are valid minimum column statistic values, and hence we should adjust the function to correctly transform and support them.
This fix is going to be crucial as we prepare to introduce Write Support.
=> [Bug Fix] TruncateTransform for falsey values

pyiceberg/transforms.py, tests/test_transforms.py
Following up on @HonahX 's comment on https://github.com/apache/iceberg-python/pull/276
=> [Bug Fix] all TimeTransforms for falsey values 

tests/conftest.py
This PR changes the default moto server port from `5000` to `5001`. Port 5000 is used by AirPlay Receiver on MacOS. 
The `is_port_in_use` function is used to check if the port is available first before starting the moto server. Moto server errors out silently when the port is already in use. This will cause tests to fail with client errors even though the issue is the moto server.
For more details, see [Issue #291 ](https://github.com/apache/iceberg-python/issues/291)
=> Fix moto server port conflict

pyiceberg/catalog/glue.py, tests/catalog/integration_test_glue.py, tests/catalog/test_glue.py
Resolves #216.
This PR adds information about the schema (on update/create) and
location (create) of the table to Glue, enabling both an improved UI
experience as well as querying with Athena.
It follows mainly the behavior in the [Java library](https://github.com/apache/iceberg/blob/e32df0ce08086758c44e9174c582638068244073/aws/src/main/java/org/apache/iceberg/aws/glue/IcebergToGlueConverter.java#L218)
=> Set Glue Table Information when creating/updating tables

pyiceberg/catalog/glue.py
While reviewing the GlueCatalog implementation in Python, I noticed the listing methods for tables and namespaces are making redundant calls to AWS Glue. This PR removes the extra call and ensures that all data retrieval and pagination handling remains consistent. 
Before:
```
print(glue_catalog.list_namespaces())
> [('default',), ('spark',)]
print(glue_catalog.list_tables("default"))
> [('default', 'amazon'), ('default', 'cmd'), ('default', 'history'), ('default', 'snapshots'), ('default', 'table3'), ('default', 'table3_copy'), ('default', 'table4')]
```
After:
```
print(glue_catalog.list_namespaces())
> [('default',), ('spark',)]
print(glue_catalog.list_tables("default"))
> [('default', 'amazon'), ('default', 'cmd'), ('default', 'history'), ('default', 'snapshots'), ('default', …
```
=> Remove redundant API call to Glue

pyiceberg/io/__init__.py, pyiceberg/io/fsspec.py, pyiceberg/io/pyarrow.py, tests/catalog/test_sql.py, tests/io/test_fsspec.py, tests/io/test_pyarrow.py
[Issue #299](https://github.com/apache/iceberg-python/issues/299)
This PR changes the behavior of both `PyArrow` and `FsSpec` file systems. When writing to the local file system, parent directories will be created first before writing to the file. Previously, a `FileNotFoundError` error is thrown when the parent directories are missing. 
Added tests to `tests/io/test_fsspec.py` and `tests/io/test_pyarrow.py`
Added `test_append_table` test to write to the local filesystem, to illustrate the issue. It fails without the changes in this PR.
Also added the `catalog_sqlite_fsspec` catalog which tests writing to the local filesystem using `FSSPEC_FILE_IO`
=> Fix writing to local filesystem

mkdocs/docs/api.md, pyiceberg/catalog/__init__.py, pyiceberg/catalog/dynamodb.py, pyiceberg/catalog/glue.py, pyiceberg/catalog/hive.py, pyiceberg/catalog/noop.py, pyiceberg/catalog/rest.py, pyiceberg/catalog/sql.py, pyiceberg/io/pyarrow.py, pyiceberg/schema.py, pyproject.toml, tests/catalog/test_base.py, tests/catalog/test_dynamodb.py, tests/catalog/test_glue.py, tests/catalog/test_sql.py, tests/conftest.py, tests/io/test_pyarrow_visitor.py
This addresses: https://github.com/apache/iceberg-python/issues/278
Added `UP037 [*] Remove quotes from type annotation` to ruff in order to support [Forward References: PEP-484](https://peps.python.org/pep-0484/#forward-references)
As discussed in the issue, we are proposing to update the create_table API to:
```
def create_table(
self,
identifier: Union[str, Identifier],
schema: Union[Schema, "pa.Schema"],
location: Optional[str] = None,
partition_spec: PartitionSpec = UNPARTITIONED_PARTITION_SPEC,
sort_order: SortOrder = UNSORTED_SORT_ORDER,
properties: Properties = EMPTY_DICT,
) -> Table:
...
if isinstance(schema, pa.Schema):
schema = pre_order_visit_pyarrow(schema, _ConvertToIcebergWithFreshIds())
...
```
We will call the function like:
```
table: pa.Table
catalog = load_catalog() …
```
=> `create_table` with a PyArrow Schema

pyiceberg/avro/file.py
Noticed this while profiling. This simplifies the code a bit.
=> Use `.read_bytes()` instead

pyiceberg/catalog/rest.py
For the other implementations, we do this when writing the metadata, but for the REST catalog, we post the schema itself.
The REST spec does not mention anything about setting fresh IDs, so it is best to do it ourselves.
=> REST: Set fresh IDs on create-table

.github/workflows/python-release.yml
We now include PyArrow in the `conftest.py`: https://github.com/apache/iceberg-python/actions/runs/7716469604
=> Add PyArrow for the Cython decoder tests

.github/workflows/python-release.yml
The build failed: https://github.com/apache/iceberg-python/actions/runs/7717856635/job/21037867863
```
Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```
=> The name needs to be unique per run

.github/workflows/python-release.yml, tests/conftest.py, tests/io/test_pyarrow.py
It looks like PyArrow binaries are not available for all architectures, and therefore it tries to compile it locally when it isn't available.
We want to avoid this since Arrow requires a rather complicated build chain.
=> Allow running the Avro decoder tests without Arrow

pyiceberg/io/pyarrow.py, pyiceberg/table/__init__.py
We currently don't set the sort-order id, which means unsorted:
> If sort order ID is missing or unknown, then the order is assumed to be unsorted.
From the spec. We don't set the sort-order, since it is optional.
If you have a process that compacts the data, that will take care of the sorting.
=> Remove sort-order constraint

pyiceberg/io/pyarrow.py, pyiceberg/table/__init__.py, tests/integration/test_writes.py
There's two different flavors to this edge case:
1. Handling of Null only columns on write
2. Support for writing empty tables / dataframes that behaves consistently with Spark
Resolves https://github.com/apache/iceberg-python/issues/337
Resolves https://github.com/apache/iceberg-python/issues/348
=> Bug fix for writing empty df or null only columns

pyiceberg/catalog/sql.py
`create_engine`'s `echo` is useful for debugging purposes.
Otherwise, it exposes a lot of internal SQLite information when it's not needed.
=> SqlCatalog, default create_engine echo to False

pyiceberg/catalog/sql.py
When sqlalchemy encounters an error if the table does not exist, it raises a different exception from sqlite. Hence, when using postgres, it is not possible to even create the catalog, as the exception is not handled (and therefore, we will not be able to do `catalog.create_tables()` either). I am able to reproduce this in tests with a postgres docker container, so I can incorporate that into these tests as another parameterized fixture if that is desired.
=> fix postgres catalog initialization when tables do not exist

pyiceberg/catalog/rest.py, pyiceberg/io/pyarrow.py, tests/integration/test_reads.py, tests/integration/test_writes.py
I had to change the `metadata_collector` code due to https://github.com/dask/dask/issues/7977.
For the `<not set>` case (no compression specified) the tests currently pass locally but they shouldn't as we never set zstd as the default. Not sure what's going on?
Should we default to gzip which is the default for Iceberg according to [this](https://iceberg.apache.org/docs/latest/configuration/) document, or should we use a more reasonable and modern default like zstd level 3?
=> Use `write.parquet.compression-{codec,level}`

pyiceberg/catalog/glue.py
Pyiceberg uses `TimestampType` for timestamp without time zone and `TimestampzType` for timestamp with time zone. 
This PR adds the missing conversion from `TimestampzType` to glue type string "timestamp". Otherwise, table creation fails with a ValueError when generating StorageDescriptor
=> Bug Fix: Allow GlueCatalog to create table with TimestampzType

.asf.yaml
Sung as a release manager, I think it would help if he can update issues himself. For example in https://github.com/apache/iceberg-python/issues/226#issuecomment-1900604096
=> Add `syun64` as collaborator

pyiceberg/io/pyarrow.py, tests/io/test_pyarrow_visitor.py
=> Arrow: Support large-string

pyiceberg/table/__init__.py, tests/integration/test_reads.py
1. Adds some integration tests for Daft
2. Realized also that our current Daft integration was implemented not on `Table` but on the Scan... This is now fixed and verified with integration tests
=> Add tests and fixes for Daft integration

mkdocs/docs/configuration.md, pyiceberg/io/pyarrow.py, pyiceberg/table/__init__.py
On top of @HonahX's work in https://github.com/apache/iceberg-python/pull/388
=> Allow setting `{row-group,page}` limit

.github/workflows/python-release.yml
With the new version, you cannot merge the different runs anymore into a single zip: https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes
Which is quite annoying since you have to merge them by hand.
=> Downgrade to the previous artifact upload action

pyiceberg/catalog/hive.py, tests/integration/test_reads.py
This PR adds locking to the hive commit path for tables.  The current commit path is unsafe as competing updates may overwrite other clients that are using locking.
This implementation is the most restrictive in that it will fail a commit if it cannot immediately acquire a lock.
=> Hive locking

pyiceberg/io/pyarrow.py, tests/integration/test_writes.py, tests/io/test_pyarrow.py, tests/io/test_pyarrow_visitor.py
This PR is to address an issue that prevented the `to_arrow` method from handling binaries larger than 2GB when used as mentioned in #344.
With this change in place, all binary types must be defined via `pa.large_binary` when defining a pyarrow schema.
I considered leaving it as `pa.binary` and casting it in pyiceberg, but since defining it as `pa.large_binary` is essential for pyarrow to handle 2GB of data, I implemented it this way.
=> Arrow: Support Large Binary when using `to_arrow`

mkdocs/docs/index.md
The correct name is `gcsfs`. https://github.com/apache/iceberg-python/blob/main/pyproject.toml#L119
=> Use the correct name of extra that adds GCS support

pyiceberg/table/__init__.py, pyiceberg/table/metadata.py, tests/catalog/test_glue.py, tests/catalog/test_hive.py, tests/catalog/test_sql.py, tests/table/test_metadata.py
Currently we always set V2 format for create table for non-rest Catalogs regardless of the specified version. This change addresses that.
=> Fix setting V1 format version for Non-REST catalogs

LICENSE, NOTICE
This reverts commit e9e265a1878a55a4385580bf800382fd75c912c9.
If I'm reading [the page right](https://infra.apache.org/licensing-howto.html) I don't think we should add this to the notice:
- Avro: Since we don't bundle the code, but just took some part of it, and want to attribute the author.
- Thrift/Hive: We don't bundle any code, but just take the Python-compiled Thrift definitions.
=> Update `LICENSE` and `NOTICE`

mkdocs/docs/how-to-release.md
=> docs: Add section on fetching the remote

.github/workflows/python-release.yml
closes: #397
This PR builds the wheels on 3 more macos versions, including `macos-14` which will build a wheel compatible with arm. ([link](https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/))
=> Chore: build wheels for all macos versions including arm macos-14

.github/workflows/python-release.yml
Bundling this by version makes it easier for the release
=> Set version in path instead of OS

pyiceberg/utils/config.py, tests/utils/test_config.py
Reported on Slack: https://apache-iceberg.slack.com/archives/C029EE6HQ5D/p1707633685716559
```bash
export PYICEBERG_CATALOG__SOMETHING__S3__REGION=eu-north-1
```
Before:
```python
>>> from pyiceberg.catalog import load_catalog
>>> load_catalog('something').properties
{'s3': {'region': 'eu-north-1'}, ...}
```
After:
```python
>>> from pyiceberg.catalog import load_catalog
>>> load_catalog('something').properties
{'s3.region': 'eu-north-1', ...}
```
Which correspondents with the key `s3.region` that we use. Now the example makes sense:
=> Fix environment variable parsing

pyiceberg/io/pyarrow.py, pyiceberg/table/__init__.py, tests/integration/test_writes.py
Add an `UpdateSnapshot` for constructing snapshots similar to the Java API, and the update schema API.
=> Make the snapshot creation part of the `Transaction`

pyiceberg/catalog/rest.py
Clients can optionally send this header to signal which delegated access pattern it can support. At this point the iceberg-python client can support `vended-credentials` and `remote-signing`, thus we can always send this header.
Addtional details about this header can be found in the REST OpenAPI spec: https://github.com/apache/iceberg/blob/main/open-api/rest-catalog-open-api.yaml#L1459-L1483
=> Send X-Iceberg-Access-Delegation header to signal support for vended credentials/remote signing

poetry.lock, pyiceberg/catalog/rest.py, pyproject.toml, tests/catalog/test_rest.py
Closes #234 
- Attempts to retry 2 more times if the initial call fails. 
- The retry is only triggered for `AuthorizationExpiredError` response.
=> Retry with new Access Token on 419 response

pyiceberg/table/__init__.py
This makes is easier to trace which data files are being written by which version of the table.
=> Reuse commit-uuid as the write-uuid

pyiceberg/table/__init__.py, pyiceberg/table/name_mapping.py, tests/integration/test_rest_schema.py, tests/table/test_name_mapping.py
Similar to the [Java implementation](https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/SchemaUpdate.java#L464), we should update the existing name_mapping on update_schema().
Some changes:
- Table.name_mapping no longer defaults to the auto-generated name_mapping based on the current Schema. We should explicitly return None if the property isn't set, so that we can use the function return value to avoid the additional steps in updating the existing name mapping.
- I've introduced some changes compared to the Java version. Specifically:
- the way it was handling reassigned names had a bug where it wasn't removing all reassigned fields, but only the last one: https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/mapping/MappingUtil. …
=> Update NameMapping on update_schema()

pyiceberg/io/pyarrow.py, tests/io/test_pyarrow_visitor.py
closes: #451
The C++ implementation of Arrow has different types of lists (https://arrow.apache.org/docs/cpp/api/datatype.html#_CPPv4N5arrow12BaseListTypeE), but these types are not correctly implemented in Python, where there is no common superclass for them, they extend the DataType class directly.
`LargeListType` and `FixedSizeListType` are also lists but with some extra characteristics, so they should be accepted by PyIceberg, and transformed to ListType as the PyArrow `ListType`.
In the mentioned issue, PyArrow map the Polars list to a `LargeListType` instead of `ListType` and that's why it fails.
=> Accept pyarrow LargeListType and FixedSizeListType

pyiceberg/catalog/__init__.py, pyiceberg/catalog/dynamodb.py, pyiceberg/catalog/glue.py, pyiceberg/catalog/hive.py, pyiceberg/catalog/rest.py, pyiceberg/catalog/sql.py
While going through some code, I noticed that these are missing
=> docstring: Fix missing commit

tests/conftest.py
While browsing `conftest.py`, I noticed `LocalOutputFile` which is [not used anywhere in the repo](https://github.com/search?q=repo%3Aapache%2Ficeberg-python%20LocalOutputFile&type=code). 
It's first introduced in [this commit](https://github.com/apache/iceberg/commit/98dc1e63d240c32ec7d48eb246d4b8bcd421aeff#diff-93c4e2e1e5b9bad7dee0662cdcc293096d159ee95665affad7ea84814d2eb738R807), originally used for `LocalFileIO`. 
Since we added the ability to write to local filesystem in #301, I believe this is no longer needed
=> Cleanup conftest, remove LocalOutputFile

tests/catalog/test_base.py
1. Adding a new schema to the `InMemoryCatalog` results in replacing the old schema as can be seen by the assertions of `test_commit_table` ([link](https://github.com/apache/iceberg-python/compare/main...anupam-saini:iceberg-python:as-fix-in-memory-ctlg?expand=1#diff-6c6a5496123dab58c6136d5f34192f77383332d680e8723066905f1c070432bdL620)). It should retain the old schema as well.
2. Opens up the catalog for other `TableUpdate` operations.
=> Fix `InMemoryCatalog` Catalog commit operation

pyiceberg/catalog/sql.py, tests/catalog/test_sql.py
There is a bug where `load_namespace_properties` for the SqlCatalog does not raise an exception if the namespace does not exist. This PR fixes it in the same convention as other functions (ref.  update_namespace_properties ) and adds a test case for it as well.
=> Raise exception if namespace does not exist in load_namespace_properties for Sql Catalog

mkdocs/docs/configuration.md, pyiceberg/catalog/rest.py, tests/catalog/test_rest.py
This PR Fixes #455 by adding ability to use custom headers in PyIceberg's RESTCatalog, making it consistent with the Java implementation of the RESTCatalog. In the Java implementation, configs have the flexibility to be specified at two points: initially, through catalog properties provided at creation, and dynamically, based on the properties included in the server's response to the getConfig endpoint call. Which ensures that all the subsequent requests are made with these headers. One thing to call out is headers are also case insensitive, and this change respects that.
**Catalog Properties**
```
catalog = RestCatalog("rest", uri=TEST_URI, warehouse="s3://some-bucket", **{"header.Content-Type": "application/vnd.api+json"})
```
**getConfig Response**
```
{
"defaults": { …
```
=> Add Support for Custom Header Configurations in RESTCatalog

pyiceberg/catalog/rest.py, tests/catalog/test_rest.py
It was refreshing on each of the calls. I think the `before_sleep` is the correct hook.
=> Fix retrying logic

pyiceberg/catalog/rest.py, tests/catalog/test_rest.py
To fix issue(https://github.com/apache/iceberg-python/issues/463). In short, Client Credential Flow's http response doesn't have the field `issued_token_type`. Make it optional to avoid validation error like this:
```
ValidationError: 1 validation error for TokenResponse
issued_token_type
Field required [type=missing, input_value={'access_token': 'eyJhbGc... 'token_type': 'bearer'},
input_type=dict]
```
cc @danielcweeks @Fokko @syun64 @RussellSpitzer
=> Make issued_token_type optional to support OAuth2 Client Credential Flow

pyiceberg/catalog/rest.py, pyiceberg/table/metadata.py, pyiceberg/typedef.py, pyiceberg/types.py, tests/catalog/test_base.py, tests/catalog/test_sql.py, tests/integration/test_writes.py, tests/table/test_init.py
Resolves #376 
We want to be able to accept types other than string type in the `properties` field of Table and TableMetadata.
For example, setting a value to an `int` type
> create_table(..., properties={"write.parquet.compression-level": 42})
This PR adds a "before" field validator to `TableMetadataCommonFields` which will transform the values of the `properties` dict to str. Note, we explicitly disallow `None` type, since the transformation will change `None` to str `"None"` which is unintuitive. 
References
* https://stackoverflow.com/questions/77304167/using-pydantic-to-change-int-to-string
* https://docs.pydantic.dev/latest/concepts/validators/#field-validators
=> Allow non-string typed values in table properties

.github/workflows/check-md-link.yml, mkdocs/docs/SUMMARY.md, mkdocs/docs/configuration.md, mkdocs/docs/index.md
#324 added Github action to check link html links in docs. There are a few dead links in the most recent run. 
https://github.com/kevinjqliu/iceberg-python/actions/runs/8124843259/job/22207404913
This PR corrects the dead links or disables checking for those particular cases. 
```
ERROR: 1 dead links found!
[✖] https://iceberg.apache.org/catalog/ → Status: 404
ERROR: 6 dead links found!
[✖] https://10.0.19.25/ → Status: 0
[✖] http://my.proxy.com:8080 → Status: 0
[✖] http://localhost/ → Status: 0
[✖] http://0.0.0.0:4443 → Status: 0
[✖] https://rest-catalog/ws → Status: 0
[✖] https://auth-service/cc → Status: 0
ERROR: 1 dead links found!
[✖] reference/ → Status: 400
```
Following instructions in 
https://github.com/gaurav-nelson/github-action-markdown-link-check
=> Fix dead links in docs

pyiceberg/catalog/rest.py, tests/catalog/test_rest.py
=> Make scope configurable

tests/catalog/test_base.py, tests/integration/test_partition_evolution.py, tests/integration/test_reads.py, tests/integration/test_rest_schema.py, tests/table/test_init.py, tests/table/test_metadata.py
This PR modifies `tests` to explicitly check `schema_id` when comparing `Schema`.
Related to #290
Previously, many tests were written with implicit `schema_id` checks. For example, 
```
assert table.schema() == Schema(
NestedField(field_id=1, name='id', field_type=LongType(), required=False),
NestedField(field_id=2, name='event_ts', field_type=TimestampType(), required=False),
NestedField(field_id=3, name='str', field_type=StringType(), required=False),
NestedField(field_id=4, name='col_string', field_type=StringType(), required=False),
schema_id=1,
identifier_field_ids=[],
)
```
Since `Schema.__eq__` does not check for `schema_id`, we never check the `schema_id` of the `Schema`
=> Tests should explicitly check for `schema_id`

pyiceberg/catalog/glue.py, tests/catalog/test_glue.py
The [upstream Iceberg documentation](https://iceberg.apache.org/docs/1.4.0/aws/#glue-catalog-id) details `glue.id` as a parameter which can be used to set the AWS Glue Catalog ID (AWS Account ID).
This is critical for scenarios where the Glue catalog exists in a separate environment from the workload running pyiceberg (e.g. an account separation between workloads and data lake).
This PR reads `glue.id` and, if set, injects `CatalogId=` as a parameter on all boto3 Glue service calls.
=> add support for glue.id

mkdocs/docs/configuration.md, pyiceberg/catalog/rest.py, tests/catalog/test_rest.py
#479 
In this PR, I have tried to provision to pass all additional optional parameter, along with audience.
=> Make optional oauth configurable

tests/conftest.py, tests/integration/test_writes.py
Fix #482
While working on #444, I couldn't get integration tests working since using `spark.sql` to count the number of data files returns the wrong result. This becomes more bizarre when Python's iceberg table state is not the same as Spark's iceberg table state. 
This PR adds a simple test to verify that "python's iceberg table snapshot id" is the same as "spark's iceberg table's snapshot id".
The culprit is the `spark.sql.catalog.catalog-name.cache-enabled` setting, which defaults to `True` and caches table metadata. 
Spark sql calls will use the cached iceberg metadata instead of the updated one. 
```
spark.sql.catalog.catalog-name.cache-enabled	true or false	Whether to enable catalog cache, default value is true
```
https://iceberg.apache.org/docs/latest/spark-configuration/#catalog-c …
=> Disable Spark Catalog caching for integration tests

pyiceberg/table/__init__.py, tests/integration/test_reads.py
Resolves #502
This PR modifies the `Transaction`s `set_properties` API to allow passing table properties either as dictionary or as kwargs
For example, 
```
with table.transaction() as transaction: 
transaction.set_properties(abc="def")
transaction.set_properties({"abc": "def"}) 
```
`set_properties` only allows table properties to be passed in either via dictionary or kwarg, not both. This removes complexity when both are set.
=> Set table properties with dictionary

pyiceberg/catalog/glue.py, pyiceberg/catalog/hive.py, pyiceberg/catalog/noop.py, pyiceberg/catalog/rest.py, pyiceberg/catalog/sql.py, pyiceberg/expressions/visitors.py, pyiceberg/io/pyarrow.py, pyiceberg/table/__init__.py, tests/catalog/test_base.py, tests/catalog/test_rest.py, tests/catalog/test_sql.py, tests/expressions/test_parser.py, tests/integration/test_writes.py, tests/io/test_pyarrow.py, tests/table/test_init.py, tests/table/test_metadata.py, tests/test_schema.py, tests/utils/test_manifest.py
This is the first batch of imports to decouple, based on issue #499.
=> Imports decouple

pyiceberg/catalog/rest.py, pyiceberg/table/__init__.py, pyiceberg/table/metadata.py, tests/integration/test_reads.py
Requires #503 to be merged first, extension of #502. 
This PR modifies `Transaction`'s `set_properties` API to accept table properties as type `Dict[str, Any]`, either as dictionary or kwargs. 
For example, 
```
with table.transaction() as transaction:
transaction.set_properties(abc=123)
transaction.set_properties({"abc": 123})
```
This is done by reusing the field validator defined in #469. Setting `None` property value is disallowed since the transformation will change None to str "None" which is unintuitive.
The Iceberg spec stores table properties as strings. That is why when setting a property value as int, reading it back produces a string.
```
table = table.transaction().set_properties({"abc": 123}).commit_transaction()
assert table.properties.get("abc") == "123"
```
Use …
=> Allow setting non-string typed values in `set_properties`

Makefile, pyiceberg/table/__init__.py, tests/integration/test_rest_schema.py
Also update name mapping if schema is updated through a Transaction.
[Related PR](https://github.com/apache/iceberg-python/pull/441)
This PR fixes the current behavior, which only updates the name mapping if UpdateSchema is created from the Table.update_schema function. Transaction.update_schema should also pass the name_mapping of the table.
```
with simple_table.transaction() as txn:
with txn.update_schema() as schema_update:
schema_update.rename_column("bar", "var")
```
=> [Bug fix] update name mapping in Transaction.update_schema

pyproject.toml
fsspec uses calendar versioning in which case the limit might not even make sense. Bumping it to another year, but you might want to consider removing the upper bound.
=> Allow fsspec up to 2025.1

poetry.lock, pyproject.toml
I forked `mmh3` under my own name to add Python 3.11 support, but I see that the original author of `mmhash3` has added support. So we can move this back now :)
=> build: Move back to the mmh3

mkdocs/docs/api.md, pyiceberg/catalog/__init__.py, pyiceberg/catalog/rest.py, tests/catalog/test_base.py, tests/catalog/test_rest.py
=> Add `table_exists` method to Catalog

pyiceberg/expressions/visitors.py, tests/expressions/test_evaluator.py
This will enable use to delete whole datafiles by evaluating the metrics, and not needing to open the Parquet files.
=> Add StrictMetricsEvaluator

pyiceberg/table/__init__.py, tests/table/test_init.py
I discovered an error when trying to deserialize the `CommitTableRequest` object.
```
request = CommitTableRequest(
requirements=(AssertTableUUID(uuid='4bfd18a3-74c6-478e-98b1-71c4c32f4163'),),
identifier=TableIdentifier(namespace=['a'], name='b'),
)
deserialized_request = CommitTableRequest.model_validate_json(request.model_dump_json())
```
raises 
`TypeError: Can't instantiate abstract class TableRequirement with abstract method validate`
I added a test to round-trip serialize/deserialize the `CommitTableRequest`.  After investigating I was able to fix it by using [Discriminated Unions](https://docs.pydantic.dev/latest/concepts/unions/#discriminated-unions), which seem like a natural fit for the `TableUpdate` and `TableRequirement`.
=> Fix CommitTableRequest serialisation

pyiceberg/table/__init__.py, pyiceberg/table/snapshots.py, tests/integration/test_writes.py, tests/table/test_snapshots.py
Changes include:
- add write.summary.partition-limit to table properties
- add changed-partition-count to snapshot summary
- add partition stats. these are key value pairs whose key is like partitiion.<partition_key> and whose value is like a nested mini-summary string concatenated by ','.
For example: 
```'partitions.int_field=1': 'added-files-size=1234,removed-files-size=1234,added-data-files=1,deleted-data-files=1,added-records=100,deleted-records=100'```
=> Add partition stats in snapshot summary

mkdocs/docs/api.md, pyiceberg/schema.py, tests/test_schema.py
Use case
```python
import pyarrow as pa
import pandas as pd
table = catalog.load_table('some_schema.table_name')
schema = table.schema().as_arrow()
data = {
'id_job': [1, 2, 3, 4],
'description': ['some text', 'some text', 'some text', 'some text']
}
df = pd.DataFrame(data)
pa_df = pa.Table.from_pandas(df, schema=schema)
table.append(pa_df)
```
=> Add as_arrow() to Schema class

tests/conftest.py
Currently, the glue integration tests fail because the real s3 client fixture is wrapped with mocking environment.
=> Fix Glue Integration test

pyiceberg/table/metadata.py, tests/table/test_metadata.py
When working on https://github.com/apache/iceberg-python/pull/498, I noticed that `new_table_metadata` cannot correctly initialize `partition_specs` and `sort_oders` fields for V1 Metadata. For example:
```python
schema = ... 
partition_spec = PartitionSpec(
PartitionField(source_id=22, field_id=1022, transform=IdentityTransform(), name="bar"), spec_id=10
)
sort_order = SortOrder(
SortField(source_id=10, transform=IdentityTransform(), direction=SortDirection.ASC, null_order=NullOrder.NULLS_LAST),
order_id=10,
)
actual = new_table_metadata(
schema=schema,
partition_spec=partition_spec,
sort_order=sort_order,
location="s3://some_v1_location/",
properties={'format-version': "1"},
)
--------   
print(actual.partition_specs)
--- output ---
[PartitionSpec(spec_id=0)]
-------- …
```
=> [Bug Fix] Fix TableMetadataV1 Validators

pyiceberg/io/pyarrow.py
Fixes #542 
`_task_to_table` returns row count instead of using shared state `row_counts`.
When a `limit` is set, Future objects running after the `row_counts` limit is achieved will just be canceled.
=> Fix race condition on `Table.scan` with `limit`

pyiceberg/expressions/visitors.py, pyiceberg/transforms.py, tests/conftest.py, tests/test_transforms.py
Can be used for detecting when manifests are part of a delete operation.
=> Add Strict projection

pyiceberg/utils/schema_conversion.py, tests/avro/test_file.py
When writing V1, the sequence-numbers should be None. For V2 they will be written and read into the original value.
=> Fix the Avro tests

pyiceberg/io/pyarrow.py, pyiceberg/table/__init__.py, tests/catalog/test_sql.py, tests/table/test_init.py
This PR resolves #520 by casting the incoming pyarrow `Table` to the same Schema as the Iceberg Table. This is safe since we first check for schema compatibility. 
* Renamed `_check_schema` -> `_check_schema_compatible`.
* Updated PR to use #532, `Schema.as_arrow()`.
* Added test for downcast schema
=> On write operation, cast data to Iceberg Table's pyarrow schema

.github/workflows/check-md-link.yml, mkdocs/docs/SUMMARY.md, mkdocs/docs/configuration.md, mkdocs/docs/index.md
This PR backports #324 and #493 to 0.6.x branch, resolving merge conflicts caused by cherry-picking
=> [0.6.x] Backport PR #324 and #493 for fixing dead links in docs

pyiceberg/io/pyarrow.py, pyiceberg/table/__init__.py, tests/catalog/test_sql.py, tests/table/test_init.py
=> [0.6.x] Backport PR #523 to cast data to iceberg table's pyarrow schema

pyiceberg/table/__init__.py, tests/catalog/test_sql.py, tests/integration/test_reads.py, tests/integration/test_writes.py
Follow up to #523 
Remove `print` in test (left it in accidentally, saw it was removed in #559)
Call `.as_arrow()` once
Uncomment test for `sqlite`
=> Minor fixes, #523 followup

pyiceberg/catalog/rest.py, tests/catalog/test_rest.py
To resolve https://github.com/apache/iceberg-python/issues/550.
=> Disallow default header to be overwritten

mkdocs/docs/how-to-release.md
Remove `-s` option from `twine` upload command since [the signature is no longer supported by PyPi](https://blog.pypi.org/posts/2023-05-23-removing-pgp/)
Copied instructions from https://iceberg.apache.org/how-to-release/#introduction for publishing GPG key in [KEYS](https://dist.apache.org/repos/dist/dev/iceberg/KEYS)
=> [Doc] Update how-to-release.md

pyiceberg/table/__init__.py, tests/integration/test_writes.py
As a followup from @HonahX 's suggestion on https://github.com/apache/iceberg-python/pull/498
This refactoring is required both for supporting CreateTableTransaction, and supporting static overwrites through delete + append
=> Move writes to Transaction

pyiceberg/io/fsspec.py, pyiceberg/io/pyarrow.py, tests/io/test_fsspec.py, tests/io/test_io.py
We cannot pickle FileIO implementations currently due to the file system initialization being inside a LruCache wrapper instance.
For example if one tries to pickle.dumps(pyarowfileIO) now they will encounter the following error.
```
_pickle.PicklingError: Can't pickle <functools._lru_cache_wrapper object at 0x75ebdf179010>: it's not the same object as pyiceberg.io.pyarrow.PyArrowFileIO._initialize_fs
```
This change implements __getstate__ and __setstate__ on PyArrowFileIO and FsSpecFileIO so that they can be pickled
This is a pre-requisite to being able to serialize the Table instance.
=> Implement __getstate__ and __setstate__ on PyArrowFileIO and FsSpecFileIO so that they can be pickled

pyiceberg/io/pyarrow.py, pyiceberg/table/__init__.py, pyiceberg/table/metadata.py, tests/integration/test_add_files.py, tests/io/test_pyarrow.py
For the partial deletes I want to do a scan on in memory metadata. Changing this API allows this.
=> Change DataScan to accept Metadata and io

pyiceberg/io/pyarrow.py, tests/conftest.py, tests/integration/test_writes/test_writes.py, tests/integration/test_writes/utils.py, tests/io/test_pyarrow.py
https://github.com/apache/iceberg-python/issues/584#issuecomment-2049204249
> If we truly read by Field-IDs the names should be irrelevant, so we should probably update our mapping to ensure we correctly project by IDs.
I think we do correctly project by IDs. The real problem is the way that we sanitize the column names.
In https://github.com/apache/iceberg-python/pull/83, we add sanitize [the file_schema](https://github.com/apache/iceberg-python/blob/main/pyiceberg/io/pyarrow.py#L982C9-L982C126) in _task_to_table with the assumption that the column name  of the parquet file follows the Avro Naming spec. However, I think the "sanitization" should be more general here: it should just ensure that the final `file_project_schema` contains the same column names of the parquet file's schema. …
=> Read: fetch file_schema directly from pyarrow_to_schema

Makefile, mkdocs/docs/api.md, pyiceberg/table/__init__.py, tests/integration/test_inspect_table.py
Time travellng on Metadata Tables allows for comparisons between two snapshots of Iceberg tables in many different and meaningful ways (files, partitions, etc)
Spark Iceberg API supports timetravel on all metadata tables except for snapshots
https://iceberg.apache.org/docs/nightly/spark-queries/?h=inspecting#time-travel-with-metadata-tables
=> Support Time Travel in InspectTable.entries

mkdocs/docs/configuration.md, pyiceberg/catalog/__init__.py, pyiceberg/catalog/glue.py, pyiceberg/catalog/hive.py, pyiceberg/table/__init__.py, tests/catalog/test_hive.py, tests/conftest.py, tests/integration/test_writes.py
=> [0.6.x] Backport #585

pyiceberg/catalog/hive.py
Fixes #588 
Hive's `alter_table` does not support transactional check unless https://issues.apache.org/jira/browse/HIVE-26882 is included. Hence, we need to load and update the metadata within the lock (in a transaction) to ensure consistency
=> [Bug Fix] HiveCatalog's _commit_table need to refresh and update the metadata in a transaction

mkdocs/docs/api.md, pyiceberg/table/__init__.py, tests/integration/test_inspect_table.py
TODO: Waiting on https://github.com/apache/iceberg-python/pull/599 to merge to introduce TimeTravel - Done
=> Add Partitions Metadata Table

tests/conftest.py, tests/integration/test_partition_evolution.py, tests/integration/test_reads.py
In test_reads.py and test_partition_evolution.py, there are redundant` catalog_rest() `and `catalog_hive()` for setting the test catalog.
This PR will unify the test catalog setting in conftest.py to enhance maintainability.
=> Tests: Unify the test catalog setting

mkdocs/docs/api.md, pyiceberg/table/__init__.py, tests/integration/test_inspect_table.py
This PR adds the Refs metadata table the existing inspect logic for Iceberg tables as listed in #511. The refs metadata table in Iceberg stores the table's known snapshot references including branches, and tags.  
```
> table.inspect.refs()
```
```
pyarrow.Table
name: string not null
type: string not null
snapshot_id: int64 not null
max_reference_age_in_ms: int64
min_snapshots_to_keep: int32
max_snapshot_age_in_ms: int64
----
name: [["testBranch","main","testTag"]]
type: [["BRANCH","BRANCH","TAG"]]
snapshot_id: [[4549716733136159472,4549716733136159472,4549716733136159472]]
max_reference_age_in_ms: [[604800000,null,15552000000]]
min_snapshots_to_keep: [[2,null,null]]
max_snapshot_age_in_ms: [[null,null,null]]
```
=> Add Refs metadata table

pyproject.toml
This release is bodged, and causes Poetry to fail when it tries to fetch the tar:
https://github.com/python-poetry/poetry/issues/9293#issuecomment-2048205226
It is being tracked:
https://github.com/pypi/warehouse/issues/15749
A fix is inbound here:
https://github.com/pypi/warehouse/pull/15795
This is a hotfix for this particular package, until the fixes from `pypi/warehouse` are out. The `post` notation is very unique: https://github.com/pypi/warehouse/issues/15749#issuecomment-2048216953 and is being used in 0.004% of the releases.
=> Exclude `docutils!=0.21` as a dependency

tests/expressions/test_literals.py
The original test with `1970-01-01T01:23:45.678` could fail on the laptop due to the different timezone.
This PR uses `1970-01-01T00:00:00.000000+00:00` ( with a UTC timezone) to fix this issue.
=> Tests: Fix unstable test_timestamp_to_date due to timezone

Makefile, mkdocs/docs/how-to-release.md, mkdocs/docs/verify-release.md
Minor edits to the "Verify Release" instructions. 
Added link to "verify release" in the release email.
Here's what the "Cast the vote" section look like in Markdown. Versus [current](https://py.iceberg.apache.org/verify-release/)
=> Verify release quality of life improvements

mkdocs/docs/contributing.md, pyiceberg/io/__init__.py
PyIceberg first started with s3fs as the default FileIO implementation because it is more lightweight. At some point we've changed the default to PyArrow since it is more feature rich.
We've missed this comment back then.
=> Change suggestions to PyArrow

dev/Dockerfile
Resolves #625 
Just for documentation purposes, the integration tests do not run on ARM processors, so we need to define the default platform as amd64.
`export DOCKER_DEFAULT_PLATFORM=linux/amd64`
=> Bump pyiceberg to 0.6.0 on integration tests

Makefile
When developers want to write an integration test,  we should add some DDLs  (create tables and insert data)  to `provision.py`.
Before running `make test-integration`, we should run `make test-integration-rebuild` to rebuild the image, which takes up a significant amount of time if the DDLs are modified frequently (the developer might make several attempts).
This PR uses `docker cp` to upload the latest `provision.py` to the running container without rebuild the image.
=> CI: Update provision.py without rebuilding the integration-test image

dev/Dockerfile
=> Bump Iceberg to 1.5.0 on integration tests

mkdocs/docs/verify-release.md
Improves the verification steps to:
- not include a hard coded version (could result in users verifying the wrong version)
- use distinct paths so that the verification directory isn't reused across versions
=> Remove hard-coded release version

pyiceberg/catalog/__init__.py, pyiceberg/catalog/glue.py, tests/catalog/integration_test_glue.py, tests/catalog/test_glue.py
In https://github.com/apache/iceberg-python/pull/498, the `createTableTransaction` API requires the `_commit_table` to handle both table update and table creation. This PR refactors Glue's `_commit_table` to re-use codes such as requirements validation, metadata update, and new metadata write between the two workflows. 
This refactoring also solves an extreme case where the table gets dropped after `_commit_table` load the current table and before `_commit_table` update the table. In the previous implementation, the code will accidently slip to the table creation workflow and incorrectly create the table.
Try to see if similar implementation pattern can be applied to Hive and Sql in https://github.com/apache/iceberg-python/pull/611
=> Refactor GlueCatalog's _commit_table

.pre-commit-config.yaml
Motivation 
pre-commit hooks are running (very) old versions, and need to be updated.
To update pre-commit hook versions, we can manually run this command
```
poetry run pre-commit autoupdate
```
Alternatively, we can use `pre-commit.ci` to automate the update. This will automatically create PRs to update the hook versions. For example, see https://github.com/tiangolo/fastapi/pull/9259
Pre-comit.ci is [free for open source repositories](https://pre-commit.ci/#pricing) 
Source
https://chrisholdgraf.com/blog/2022/precommit-autoupdate/
https://pre-commit.ci/
Reference
https://github.com/tiangolo/fastapi/blob/1d41a7d2df5714e6598b541cac3cac5859b3ad4b/.pre-commit-config.yaml#L23
=> Use `pre-commit.ci` to automatically update pre-commit hook versions

pyiceberg/io/pyarrow.py, tests/io/test_pyarrow.py
When I try to test write support for Iceberg table on HDFS,  there is an error.
```
File "/home/root/anaconda3/lib/python3.8/site-packages/pyiceberg/io/pyarrow.py", line 244, in exists
self._file_info()  # raises FileNotFoundError if it does not exist
File "/home/root/anaconda3/lib/python3.8/site-packages/pyiceberg/io/pyarrow.py", line 226, in _file_info
file_info = self._filesystem.get_file_info(self._path)
File "pyarrow/_fs.pyx", line 584, in pyarrow._fs.FileSystem.get_file_info
File "pyarrow/error.pxi", line 154, in pyarrow.lib.pyarrow_internal_check_status
File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: GetFileInfo must not be passed a URI, got: hdfs://clusterXX/user/my_db/my_table/metadata/xxxxx.metadata.json
```
The root cause is that …
=> Bug Fix: Return the parsed path without schema/netloc for HDFS

pyiceberg/utils/decimal.py, tests/utils/test_decimal.py
```python
>>> (32768).bit_length()
16
```
From https://docs.python.org/3/library/stdtypes.html#int.bit_length
> Return the number of bits necessary to represent an integer in binary, excluding the sign and leading zeros
Fixes #669
=> Bug: Take signed bit into account

pyiceberg/io/pyarrow.py
Renamed class variable in PyArrowFile from ._fs to _filesystem, in order to assign with the __init()__ method the Object FileSystem to the class, and not to the single instance of the Class, as it was happening before.
=> Changed class variable names in pyarrow.py

pyiceberg/catalog/__init__.py, tests/catalog/integration_test_dynamodb.py, tests/catalog/integration_test_glue.py, tests/catalog/test_dynamodb.py, tests/catalog/test_glue.py, tests/catalog/test_sql.py
* Implementation of table_exists method at Initialization level already exists bypassing it.
* Unit Test for glue, sqlcatalog and dynamodb.
* Integration test for glue and dynamodb.
=> table_exists unit/integration test for NoSuchTableError

tests/integration/test_reads.py, tests/integration/test_writes/test_writes.py, tests/integration/test_writes/utils.py
This is not allowed in Avro, just checking if it works.
=> Test: Add test to partition on field with a dot

pyiceberg/catalog/__init__.py, pyiceberg/catalog/rest.py, tests/catalog/test_base.py, tests/catalog/test_dynamodb.py, tests/catalog/test_glue.py, tests/catalog/test_hive.py, tests/catalog/test_rest.py, tests/catalog/test_sql.py
Hi,
this is intended to resolve https://github.com/apache/iceberg-python/issues/606.
Changes:
- use `rstrip("/")` when a location is specified for `create_table`
- added tests for `DynamoDbCatalog`, `GlueCatalog`, `HiveCatalog`, `RestCatalog` and `SqlCatalog`
=> Remove trailing slash from table location when creating a table

pyiceberg/table/__init__.py, tests/integration/test_add_files.py
Issue https://github.com/apache/iceberg-python/issues/694
I'm not sure where to add tests. Is `tests/catalog/test_glue.py` the right place?
=> Make `add_files` to support `snapshot_properties` argument

pyiceberg/io/pyarrow.py, tests/integration/test_writes/test_writes.py, tests/io/test_pyarrow_visitor.py
Fixes: https://github.com/apache/iceberg-python/issues/450
DictionaryType is a separate type in Arrow, but isn't in Parquet.
Similar to how [Arrow handles Dictionary Types](https://github.com/apache/arrow/blob/22f88fa4a8f5ac7250f1845aace5a78d20006ef2/cpp/src/parquet/arrow/schema.cc#L419-L427), we will simply infer the Iceberg Type from the `value_type` of the provided `DictionaryType` field.
=> Add support for categorical type

tests/integration/test_writes/test_writes.py
=> Test, write subset of schema

pyiceberg/catalog/hive.py, pyiceberg/exceptions.py, pyiceberg/table/__init__.py, tests/catalog/test_hive.py, tests/integration/test_reads.py
In the current hive catalog implementation, locking will only be executed once.
If another task has already locked the target table, the locking will fail inevitably.
Since Iceberg-Java has implemented retry on `org.apache.iceberg.hive.MetastoreLock`, we could refer this to improve Iceberg-python.
This PR adds retry and wait logic for hive catalog with the following modifications.
1.  add `_wait_for_lock` on hive catalog
2. add `WaitingForLockException`
3. add a new UT that two tasks are locking the same table.
=> Hive catalog: Add retry logic for hive locking

pyiceberg/catalog/__init__.py, tests/catalog/integration_test_dynamodb.py, tests/catalog/integration_test_glue.py, tests/catalog/test_rest.py, tests/catalog/test_sql.py
=> Add create_namespace_if_not_exists method

pyiceberg/catalog/glue.py, tests/catalog/integration_test_glue.py, tests/catalog/test_glue.py
- If a user has an existing Iceberg table that is not yet registered in the AWS Glue Catalog, and they want to register that table in the Glue Catalog for better future access and management.
- Unit test 
- Integration Test
=> [FEAT]register table using iceberg metadata file via pyiceberg

mkdocs/docs/api.md, pyiceberg/table/__init__.py, tests/integration/test_inspect_table.py
This PR adds the manifests metadata table the existing inspect logic for Iceberg tables as listed in #511. The manifests metadata table in Iceberg shows the current file manifests for a given table. 
Java implementation: https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/ManifestsTable.java
```
table.inspect.manifests()
```
```
pyarrow.Table
content: int8 not null
path: string not null
length: int64 not null
partition_spec_id: int32 not null
added_snapshot_id: int64 not null
added_data_files_count: int32 not null
existing_data_files_count: int32 not null
deleted_data_files_count: int32 not null
added_delete_files_count: int32 not null
existing_delete_files_count: int32 not null
deleted_delete_files_count: int32 not null
partition_summaries: list<item: …
```
=>  Add manifests metadata table

pyiceberg/catalog/rest.py, tests/catalog/test_rest.py
Fixes https://github.com/apache/iceberg-python/issues/735
=> Fix: Table-Exists if Server returns 204

pyiceberg/catalog/__init__.py, pyiceberg/catalog/sql.py, pyiceberg/cli/console.py, tests/catalog/test_sql.py, tests/conftest.py
When comparing the Python implementation of SqlCatalog with the Java implementation (JdbcCatalog), I have noticed some differences that this PR tries to address.  In my opinion, we should be able to read from the same catalog database, using both the Java or Python implementations with no impact.
Here is a list of changes proposed by this PR:
- The Java implementation supports hierarchical namespaces, or multi-level namespaces separated by `.`.  For example, `ns1.ns2.ns3` is a valid namespace in Java, but not with the current Python implementation.  Identifiers will now have an optional catalog_name, zero or more namespaces and a table_name.  For example, an identifier for table `catalog_name.ns1.ns2.ns3.table_name` will be represented as the following tuple: `("catalog_name", "ns1", …
=> Introduce hierarchical namespaces into SqlCatalog

Makefile, pyiceberg/partitioning.py, pyiceberg/table/__init__.py, pyiceberg/transforms.py, tests/conftest.py, tests/integration/test_writes/test_partitioned_writes.py, tests/test_transforms.py
reopening https://github.com/apache/iceberg-python/pull/703 due to issues with git diff detection on the PR
=>  Support Appends with TimeTransform Partitions

pyiceberg/io/pyarrow.py, tests/io/test_pyarrow.py
Add flag to include/exclude Parquet field IDs to pyarrow schema
Fixes: https://github.com/apache/iceberg-python/issues/788
=> `include_field_ids` flag in `schema_to_pyarrow`

pyiceberg/table/__init__.py
In the [java implementation](https://github.com/apache/iceberg/blob/c7de6cb345995cb47312edbef6edae2f17fb8aba/core/src/main/java/org/apache/iceberg/UpdateRequirements.java#L50), AssertTableUUID is required on all table update operations, except for table creation.
This is because AssertTableUUID guards against concurrency issues that can occur when different processes are dropping and creating the Iceberg table of the same name while an update is being built.
=> AssertTableUUID on all Transactions except CreateTableTransaction

pyiceberg/io/pyarrow.py, tests/catalog/test_sql.py, tests/conftest.py, tests/integration/test_writes/test_writes.py, tests/io/test_pyarrow.py, tests/io/test_pyarrow_visitor.py, tests/test_schema.py
Fixes #791 
For consistency, we should always cast to large types when inferring pyarrow schema from Iceberg Schema, and when scanning using the physical_schema of the fragment
=> Cast PyArrow schema to `large_*` types

pyiceberg/table/snapshots.py, tests/conftest.py, tests/table/test_init.py
When I was running some tests in production, I discovered this error.
=> Fix ancestors_of exception for tables with >=2000 snapshots

mkdocs/docs/api.md, pyiceberg/io/pyarrow.py, pyiceberg/table/__init__.py, tests/integration/test_reads.py
- `RecordBatchReader` is preferable for memory constrained applications
- update `to_requested_schema` to take pa.RecordBatch instead of pa.Table
Question: pyarrow schema is currently inconsistent - it either returns pyarrow schema without Parquet metadata, or it adds the Parquet metadata and returns the value in some cases - we should make this consistent across our table scans and update the unit tests accordingly. 
Edit: Opened up the Issue here to discuss above question https://github.com/apache/iceberg-python/issues/788
=> Support `Table.to_arrow_batch_reader` to return RecordBatchReader instead of a fully materialized Arrow Table

pyiceberg/manifest.py, tests/utils/test_manifest.py
It should write the fields instead of the full spec: https://github.com/apache/iceberg-python/issues/208#issuecomment-2183015146
Also, did a small OOP refactor.
=> 🐛 Write fields instead of spec object

mkdocs/mkdocs.yml
Fixes #808
It seems that enabling the `toc` extension and its `permalink` option should enable anchors in the section headers as per https://python-markdown.github.io/extensions/toc/#usage
=> Add mkdocs toc config section

mkdocs/docs/api.md, pyiceberg/table/__init__.py, tests/integration/test_inspect_table.py
=> Add history inspect table

pyiceberg/types.py, pyiceberg/utils/singleton.py, tests/conftest.py, tests/table/test_init.py, tests/test_types.py
The IcebergRootModel inherits from Pydantic RootModel, which has its own implementation of deepcopy. When deepcopy runs, it calls this `__deepcopy__` method and ignores that it's a Singleton. So, my solution was to change the order of inheritance and implement a `__deepcopy__` method for singletons that returns itself.
https://github.com/pydantic/pydantic/blob/f024d03b832d1bbcbadf76184ed14d92571a71ca/pydantic/root_model.py#L108-L116
=> Fix deepcopy of primitive types

dev/hive/Dockerfile
I'm having some issues with the Hive 3.1.3 images on my new MacBook. The Hive 4.x images are also available for the arm64 architecture.
Resolves https://github.com/apache/iceberg-python/issues/835
=> Bump CI to Hive 4

pyiceberg/types.py, pyiceberg/utils/config.py, tests/test_types.py
Python 3.12 has dropped support for distutil package [PEP632](https://peps.python.org/pep-0632/) and any util imported via the same, will no longer be supported in 3.12 venv.
Closes #859
=> strtobool support for python 3.12

pyiceberg/catalog/sql.py, tests/catalog/test_sql.py
Fixes 3rd bug listed at https://github.com/apache/iceberg-python/issues/864, where update_namespace_properties function only updates the first property and drops the rest
=> fix: update all namespace properties in update_namespace_properties

pyiceberg/catalog/sql.py, tests/catalog/test_sql.py
Fixes bug listed at #864, where `drop_namespace` was not raising an error when the given namespace does not exist.
=> Raise error on nonexistent namespace on sql.py

pyiceberg/catalog/rest.py, tests/catalog/test_rest.py
Fixes bug listed at #864, where `drop_namespace` on rest.py was not handling an error when trying to drop a non-empty namespace.
=> Handle error when trying to drop a non-empty namespace on rest.py

mkdocs/docs/configuration.md, pyiceberg/catalog/sql.py, tests/catalog/test_sql.py
When running code for a long time using the SQLCatalog, it is possible to face a situation where a DB connection from the pool has timed out.  When trying to use that connection again, the SQLAlchemy engine raises the following exception (when using a PostgreSQL backend):
```
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) SSL SYSCALL error: EOF detected.
```
This happens when the connection has been closed by the server and the engine raises this exception.  My solution is fairly simple, but effective: when creating the engine, use `pool_pre_ping`.
```python
self.engine = create_engine(uri_prop, echo=echo, pool_pre_ping=True)
```
I can reproduce the problem with a Postgresql DB and the following code:
```python
from time import sleep
from pyiceberg.catalog import …
```
=> Add pool_pre_ping param to SQLCatalog and fix echo parsing logic

Makefile, mkdocs/docs/contributing.md
This PR introduces a make clean command in the Makefile to automate the removal of old cached files. The make clean command will find and delete files with specific extensions that are typically generated during the Cython build process.
closes: https://github.com/apache/iceberg-python/issues/875
=> Makefile clean utility to remove cython cached objects

pyiceberg/manifest.py, pyiceberg/table/__init__.py, tests/avro/test_file.py, tests/utils/test_manifest.py
Implements: https://github.com/apache/iceberg-python/issues/893
=> Rename data_sequence_number to sequence_number in ManifestEntry

pyiceberg/io/pyarrow.py, pyiceberg/table/__init__.py, tests/io/test_pyarrow.py, tests/table/test_init.py
Implements https://github.com/apache/iceberg-python/issues/896
Moves `_determine_partitions` and helper method `_get_table_partitions` and `TablePartition` class to `pyiceberg,io.pyarrow` module.
The tests for `_determine_partitions` method are moved to `test_pyarrow.py`
=> Move determine_partitions and helper methods to io.pyarrow

pyiceberg/io/pyarrow.py
Fixes: https://github.com/apache/iceberg-python/issues/862
It sounds like an unlikely edge case for subset of a column's rowgroup's to have stats and not the others, but as @cgbur explains in the above issue, this is the right way to be keeping track of whether the stats should be invalidated - instead of only allowing the last row group's stats validity produce the stats.
thanks @cgbur for reporting the issue!
=> fix DataFileStats invalidation logic

pyiceberg/io/pyarrow.py, pyiceberg/table/__init__.py, tests/conftest.py, tests/integration/test_add_files.py, tests/integration/test_writes/test_partitioned_writes.py, tests/integration/test_writes/test_writes.py, tests/io/test_pyarrow.py
This ended up being a lot simpler than I had thought it would be.
"Etc/UTC" is just another representation of UTC, and should be safe to support. This will allow us to support arrow dataframes produced with datetimes from libraries like pendulum that use this timezone.
Fixes: https://github.com/apache/iceberg-python/issues/863
=> support PyArrow timestamptz with Etc/UTC

pyiceberg/types.py, tests/cli/test_console.py, tests/test_types.py
Implements https://github.com/apache/iceberg-python/issues/919
=> Set boolean values in table properties to lowercase string

pyiceberg/table/name_mapping.py, tests/table/test_name_mapping.py
Attempt to fix #925. 
As described in the issue, the [Iceberg spec](https://iceberg.apache.org/spec/#column-projection) permits an empty list of names in the default name mapping. `check_at_least_one` is therefore unnecessary.
=> Allow empty `names` in mapped field of Name Mapping

pyiceberg/io/pyarrow.py, pyiceberg/schema.py, pyiceberg/table/__init__.py, tests/conftest.py, tests/integration/test_add_files.py, tests/integration/test_writes/test_writes.py, tests/io/test_pyarrow.py
Another attempt at fixing #674 
This PR is motivated by work started off by @kevinjqliu in https://github.com/apache/iceberg-python/pull/829
- it enables support for writing dataframes that are a subset of the Iceberg Table's schema
- it enables support for writing dataframes that have fields in any arbitrary order
- we convert the pyarrow schema to Iceberg Schema using the name mapping of the Table, and checks for nullability and type consistency.
Here we introduce terminologies `requested_schema` to refer to the Iceberg Table schema we are checking against, and the `provided_schema` which represents the schema of the Dataframe we are attempting to write.
A field is considered compatible if satisfies the following checks:
- An `optional` field in the `requested_schema` can be `required`, …
=> Allow writing `pa.Table` that are either a subset of table schema or in arbitrary order, and support type promotion on write

.github/workflows/python-release.yml
Attempting to resolve an issue with repairing the wheel on macos.
Source that makes this recommendation for the potential fix: https://github.com/pypa/cibuildwheel/issues/1828
Using multiple python version syntax from: https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md
Download and set up multiple Python versions:
```
jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- uses: actions/setup-python@v5
with:
python-version: |
3.8
3.9
3.10
- run: python my_script.py
```
=> uses actions/setup-python@v5 with python 3.8

.github/workflows/python-release.yml
macos-11 is no longer a supported runner:
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
=> Remove macos-11 runners from Github Actions Python Release

poetry.lock, pyproject.toml
numpy 2.0.0+ has been released, which isn't compatible with pandas <2.0.3
We should limit the upper bound on the numpy version until we are ready to upgrade the lower bound on the pandas versions.
```
________ ERROR collecting tests/integration/test_writes/test_writes.py _________
tests/integration/test_writes/test_writes.py:26: in <module>
import pandas as pd
/root/.cache/pypoetry/virtualenvs/pyiceberg-5WetIcE4-py3.9/lib/python3.9/site-packages/pandas/__init__.py:22: in <module>
from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
/root/.cache/pypoetry/virtualenvs/pyiceberg-5WetIcE4-py3.9/lib/python3.9/site-packages/pandas/compat/__init__.py:25: in <module>
from pandas.compat.numpy import (
/root/.cache/pypoetry/virtualenvs/pyiceberg-5WetIcE4-py3.9/lib/py …
```
=> Fix: Set Numpy Version Upper Limit `numpy = { version = "^1.22.4", optional = true }`

pyiceberg/expressions/__init__.py, pyiceberg/io/pyarrow.py, pyiceberg/table/__init__.py, tests/integration/test_deletes.py, tests/io/test_pyarrow.py, tests/io/test_pyarrow_visitor.py
for issue https://github.com/apache/iceberg-python/issues/954
=> fix table.delete()/overwrite() with null values

mkdocs/docs/configuration.md, pyiceberg/catalog/__init__.py, tests/catalog/test_base.py, tests/catalog/test_sql.py
Closes #938 
@HonahX followed your suggested direction, let me know what you think!
=> Support loading custom catalog impl

pyiceberg/table/__init__.py, tests/catalog/test_glue.py, tests/catalog/test_sql.py, tests/table/test_init.py
Fixes: https://github.com/apache/iceberg-python/issues/948
Updates `last-updated-ms` for DDL operations like updating schema, properties, partition spec etc.
In `update_table_metadata` if `last_updated_ms` is not updated after invoking `_apply_table_update`, then set it current timestamp in milliseconds.
**Note**:
This [line](https://github.com/apache/iceberg-python/blob/main/tests/table/test_init.py#L600) seems like a no-op, but with this change a new metadata file will be generated.
@HonahX @kevinjqliu Please suggest if there is better way to handle this.
=> Update last-updated-ms for DDL operations

mkdocs/docs/verify-release.md
To allow spinning up containers for `make test-coverage`, we now run `make install` directly on the unzipped release project directory, which will create a fresh python environment with all dependencies.
=> Update PyIceberg Verify Release doc

pyiceberg/table/__init__.py, tests/integration/test_deletes.py
Fixes: https://github.com/apache/iceberg-python/issues/979
=> Bug Fix: use appropriate partition spec for delete

pyiceberg/table/__init__.py, tests/catalog/test_sql.py, tests/integration/test_writes/test_writes.py
Fix #980 
When in a transaction, we should use `self.table_metadata` when we need metadata info from the target table, since`self.table_metadata` includes staged updates
cc @Fokko
=> [Bug Fix]Use `self.table_metadata` when in transaction

dev/provision.py, pyiceberg/io/pyarrow.py, tests/integration/test_reads.py
Fixes #992.
Empty `pyarrow` arrays are considered falsy, which caused a `ResolveError` for required fields during scan operations.
=> Fix: accept empty arrays in struct field lookup

.asf.yaml
- remove kevin and sung from the list (committer permissions overrides collaborator)
- add ndrluis as collaborator
https://github.com/apache/iceberg-python/pulls/ndrluis
=> Add ndrluis as collaborator

pyiceberg/catalog/rest.py, tests/catalog/test_rest.py
While testing PyIceberg with Polaris and multi-level namespacing, I noticed a behavior that doesn't [align with the REST catalog specification](https://github.com/apache/iceberg/blob/main/open-api/rest-catalog-open-api.yaml#L210-L215). The expected response should be the fully qualified namespace.
=> Fix list namespace response in rest catalog

poetry.lock, pyproject.toml
Adjusts the supported Python versions to exclude 3.9.7, as importing the catalog module on this version results in an unexpected error. The issue does not occur in versions 3.9.6 or 3.9.8, indicating a specific incompatibility with Python 3.9.7.
Related to #500, #497
=> Exclude Python 3.9.7 due to import error in catalog module

mkdocs/docs/configuration.md, mkdocs/docs/contributing.md, mkdocs/docs/how-to-release.md, pyiceberg/catalog/__init__.py, pyiceberg/catalog/rest.py, pyiceberg/utils/deprecated.py, tests/catalog/test_rest.py, tests/utils/test_deprecated.py
The purpose of this PR is to follow the OAuth property standard as defined in the Java implementation and the REST Catalog specification: https://github.com/apache/iceberg/blob/main/open-api/rest-catalog-open-api.yaml#L144-L145.
Deprecation message about the oauth tokens behavior:
Deprecation message about the property:
=> Deprecate rest.authorization-url in favor of oauth2-server-uri

pyiceberg/catalog/__init__.py, pyiceberg/catalog/dynamodb.py, pyiceberg/catalog/glue.py, pyiceberg/catalog/hive.py, pyiceberg/catalog/rest.py, pyiceberg/catalog/sql.py, pyiceberg/expressions/parser.py, pyiceberg/table/__init__.py, pyiceberg/utils/deprecated.py, tests/catalog/test_base.py, tests/catalog/test_rest.py, tests/catalog/test_sql.py, tests/integration/test_writes/test_writes.py
Today in PyIceberg, we have support for identifier parsing in public APIs
belonging to two different classes:
- Catalog class: load_table, purge_table, drop_table
- Table class: scan
These APIs currently have optional support for the identifier that the
instance itself belongs to.
For example, the catalog class APIs support:
```
catalog = load_catalog(“animals”, **properties)
catalog.load_table(“cats.whiskers”)
```
But it also supports:
`catalog.load_table(“animals.cats.whiskers”)`
Which is redundant, because the catalog.name is already “animals”.
Similarly, row_filter in the Table scan API supports:
```
table = catalog.load_table(“cats.whiskers”)
table.scan(row_filter=”n_legs== 4”)
```
But we also support
`table.scan(row_filter=”whiskers.n_legs == 4”)`
Which is also redundant, because …
=> Deprecate Redundant Identifier Support in TableIdentifier, and row_filter

pyiceberg/io/pyarrow.py, tests/integration/test_deletes.py, tests/integration/test_reads.py
Fixes: https://github.com/apache/iceberg-python/issues/1024
As well as a correctness issue when reading MOR tables with positional deletes
=> Fix: Handle Empty RecordBatch within `_task_to_record_batches`, fix correctness issue with positional deletes

pyiceberg/table/__init__.py, tests/integration/test_writes/test_writes.py
=> Fix overwrite when filtering all the data

mkdocs/docs/configuration.md
Property is listed twice, once with an older default value.
=> DOCS: Remove older row for `write.parquet.row-group-limit`

pyiceberg/io/pyarrow.py, tests/integration/test_reads.py
=> [bug] fix reading with `to_arrow_batch_reader` and `limit`

Makefile, tests/integration/test_reads.py
This PR implements:
- Run unit tests as part of the CI
- Add a missing integration mark to one of the integration tests
Should close #1051
=> Coverage Run unit tests first before docker containers are set up

mkdocs/docs/verify-release.md
Now that `make test-coverage` includes both unit and integration tests (thanks to #1055) 
We no longer need to specify`make test` individually
=> Update "verify release" instruction

poetry.lock, pyproject.toml
Currently, when users try to install using poetry with python3.12, they run into the following error:
```
- Installing numpy (1.24.4): Failed
ChefBuildError
Backend 'setuptools.build_meta:__legacy__' is not available.
Cannot import 'setuptools.build_meta'
at venv/lib/python3.12/site-packages/poetry/installation/chef.py:164 in _prepare
160│
161│                 error = ChefBuildError("\n\n".join(message_parts))
162│
163│             if error is not None:
→ 164│                 raise error from None
165│
166│             return path
167│
168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:
Note: This error originates from the build backend, and is likely not a problem with poetry but with numpy (1.24.4) not supporting PEP 517 builds. You can verify this …
```
=> Fix Install Issues with `docutils = 0.21.post1` and exclude 3.12 from supported python dependencies

mkdocs/docs/api.md
Copying over a similar sentence from the Java docs: https://iceberg.apache.org/docs/1.5.1/java-api-quickstart/#create-a-schema. Based on my reading of the catalog code, this is true as all the `create_table` implementations end up calling `assign_fresh_schema_ids`, `assign_fresh_partition_spec_ids`, and `assign_fresh_sort_order_ids`.
This is useful to understand so newcomers don't have to worry about ID management in any new schemas they are sending into `create_table`.
=> Update create table doc to clarify ID re-assignment

mkdocs/docs/how-to-release.md
The current `twine upload` command in the docs results in `Unknown distribution format` error due to the signature files.
https://discuss.python.org/t/gpg-signature-support-removed-from-pypi/27014
=> DOCS: Exclude signature files from twine upload

poetry.lock, pyproject.toml
We rely on the 'promote_options' argument in the 'concat_tables' method, which is only supported in version 14.0 and above.
Solves #1089
=> Increase the minimal required pyarrow version to 14.0.0

pyiceberg/catalog/rest.py, tests/catalog/test_rest.py
I understand that it might seem odd to return false for a 200 status code, but according to the [specification](https://github.com/apache/iceberg/blob/97e034b2cec9408a6f792c410a8eb8dddb452e14/open-api/rest-catalog-open-api.yaml#L833-L864), success should only be indicated by a 204 status code. Additionally, it doesn’t make sense to throw an exception for a 404 status code since a table_exists method is expected to return True or False, not just True or an exception.
If a user needs to handle exceptions, they can use the load_table method, which will return an exception if the table does not exist.
Solves: #1018
=> Fix `table_exists` behavior in REST catalog

Makefile
- Added a help command to display all commands having ## comments 
- Improved how poetry being installed 
- (Personally, i have this installed via pipx, still pip install user wide tool should have `--user` added)
=> fix: improve makefile

pyiceberg/table/__init__.py, pyproject.toml, tests/table/test_init.py
Fixes [issue#1079](https://github.com/apache/iceberg-python/issues/1079#event-13959963106)
`update_column` should be able to update / remove `doc`; and `required` if field is not an identifier field.
=> fix (issue-1079): allow update_column to set doc as ''

pyiceberg/table/__init__.py, tests/integration/test_add_files.py
This resolves #998 , where duplicate files are added  with add_files method, handles 2 cases:
1. Files list is not unique 
2. One of the files added is already referenced by current snapshot
=> prevent adding duplicate files 

pyiceberg/io/pyarrow.py, tests/integration/test_writes/test_writes.py
Similar to seeing a sort-order, I don't think we want to fail on this
=> Emit warnings instead of failing when seeing unsupported configuration

.github/workflows/python-ci.yml, .github/workflows/python-release.yml, poetry.lock, pyproject.toml
This PR adds support for python 3.12 to the PyIceberg project. It includes building and releasing for python version 3.12.
* Tested change to `python-ci` Github Action; works for python 3.12 ([Github Action run](https://github.com/apache/iceberg-python/actions/runs/10654920827/job/29531809732?pr=1068))
* Tested change to `python-release` Github Action; works for python 3.12 ([Github Action run](https://github.com/kevinjqliu/iceberg-python/actions/runs/10654960495) via my forked repo)
Pre-req: #1118, update markdown linter to use `markdownlint` which supports python 3.12
Closes #28
=> Support python 3.12

pyiceberg/catalog/__init__.py, pyiceberg/catalog/dynamodb.py, pyiceberg/catalog/glue.py, pyiceberg/catalog/hive.py, pyiceberg/catalog/noop.py, pyiceberg/catalog/rest.py, pyiceberg/catalog/sql.py, pyiceberg/table/__init__.py, tests/catalog/test_base.py, tests/catalog/test_rest.py
This was brought up earlier, and I think this is a good idea. I changed the signature to also pass in the table.
=> Make `commit_table` public

pyiceberg/types.py, tests/test_types.py
The `field_by_name` method in `StructType` seems to have inverted logic on the `case_sensitive` parameter.
=> fix: Invert `case_sensitive` logic in StructType

pyiceberg/table/update/snapshot.py, tests/integration/test_writes/test_writes.py
=> Use the correct spec when rewiting existing manifests

pyiceberg/table/update/spec.py, tests/integration/test_partition_evolution.py
Fixes: https://github.com/apache/iceberg-python/issues/1131
=> Bug Fix: Use historical partition field name

pyiceberg/catalog/__init__.py
resolves: #1163
remove this line. no additions necessary as other `Catalog` method's don't have additional context in the docstring beyond docmenting the signature
=> fix: remove old, incorrect docstring

pyiceberg/table/__init__.py, pyiceberg/table/update/schema.py, pyiceberg/table/update/snapshot.py, tests/table/test_init.py
In #1144, we moved 'public' classes and functions to submodules.
Although 'public' by naming convention, these classes and functions are meant for internal use. The current lack of explicit external API declarations makes it difficult to communicate with our end-users, which classes and functions we are intending to support for external use. (https://github.com/apache/iceberg-python/issues/1099)
The classes that were moved and are not referenced as an import in `pyiceberg.table` module are as follows:
- Move
- MoveOperation
- DeleteFiles
- FastAppendFiles
- MergeAppendFiles
- OverwriteFiles
- UpdateTableMetadata
UpdateTableMetadata is an abstract base class, and hence cannot be used directly.
This PR proposed to rename these as 'private' classes with single underscore prefix, and …
=> Preserve Backward compatibility in 0.8.0 for #1144

pyiceberg/catalog/rest.py
Found this bug while working on the REST catalog. 
This PR should be safe since `_identifier_to_tuple_without_catalog` was added in #994, and soon the "catalog name" will be fully deprecated from the table identifier. 
Also, I made sure that every `_split_identifier_for_path` in `rest.py` has a corresponding `_identifier_to_tuple_without_catalog` call.
=> [bug] [REST] Dont remove identifier root

pyiceberg/partitioning.py, tests/integration/test_partition_evolution.py
Hi, 
this is fixing a minor bug where partition evolution in combination with a `MonthTransform` could raise an exception:  https://github.com/apache/iceberg-python/issues/1156
=> fix: support MonthTransform for partitioning

mkdocs/docs/api.md, pyiceberg/table/inspect.py, tests/integration/test_inspect_table.py
Implements metadata tables for `data_files` and `delete_files` - https://github.com/apache/iceberg-python/issues/1053
Have reused the logic of `files` to derive `data_files` and `delete_files`.
Also reused the test cases for files (`test_inspect_files`) as schema is same as `files`.
=> Add metadata tables for `data_files` and `delete_files`

pyiceberg/io/pyarrow.py, pyiceberg/table/__init__.py, tests/io/test_pyarrow.py
PR #1119 
- Use ArrowScan.to_table to replace project_table in these files: 
- pyiceberg\table\__init__.py
- pyiceberg\io\pyarrow.py
- pyiceberg\test_pyarrow.py
=> Use ArrowScan.to_table to replace project_table

pyiceberg/table/__init__.py
https://github.com/apache/iceberg-python/issues/1190
=> Add Docstrings to `pyiceberg/table/__init__.py`

.github/workflows/python-release.yml, poetry.lock, pyproject.toml
Allow python 3.12 to run poetry. 
Changed to use caret requirements, same logic. Greater than or equal to 3.8, less than 3.13 which is currently in pre-release.
Changed from `<=` to `<` because sometimes, `3.12.6` doesn't match `<= 3.12`, `<3.13` is fixes that
https://python-poetry.org/docs/dependency-specification/#caret-requirements
https://www.python.org/doc/versions/
=> Support python 3.12 in poetry

poetry.lock, pyiceberg/manifest.py, pyiceberg/table/snapshots.py, pyproject.toml, tests/utils/test_manifest.py
Closes #595, Reverts #787, Closes #1162
Reimplement manifest list cache using the `cachetools` library. This keeps the manifest list cache as a global cache and introduces the ability to specify the cache key as only `manifest_list`.
The cache result is stored as `Tuple` instead of `List` to prevent modification 
Move the `_manifests` function from `snapshots.py` to `manifest.py` since its a global manifest cache and not specific to any 1 snapshot
=> Use `cachetools's LRUCache` to cache manifest list 

pyiceberg/io/pyarrow.py, tests/integration/test_deletes.py
Fixes: #1132 
Culprit was the awkward zero-copy pass back and forth between RecordBatch and Table to filter by pyarrow_filter.
https://github.com/apache/iceberg-python/blob/0dc54080aa287dc8e920da128d7f4b335965f1df/pyiceberg/io/pyarrow.py#L1246-L1254
As noted, this is necessary because passing an expression filter to a RecordBatch hasn't yet been exposed (it is now in 17.0.0, but that would raise the lower limit of PyArrow dependency that much higher).
In cases where a single RecordBatch -> a Table -> multiple RecordBatches because of how Arrow automatically chunks a Table into multiple RecordBatches, we would lose the remaining RecordBatches in the returned output. Essentially, there's no guarantee that a single RecordBatch will remain a single one in a round trip conversion to Arrow …
=> Bug Fix: Position Deletes + row_filter yields less data when the DataFile is large

mkdocs/docs/contributing.md
Remove dead loom link, causing CI to fail
https://github.com/apache/iceberg-python/actions/runs/11115020853/job/30884767054?pr=1211
=> Remove dead loom link

.github/workflows/python-ci.yml, .github/workflows/python-integration.yml, .github/workflows/python-release.yml, mkdocs/docs/contributing.md, poetry.lock, pyproject.toml
This PR drops support for Python 3.8 as successfully voted on the Mailing List here: https://lists.apache.org/thread/50jjtdyfovwqbw8mp5m6rfgmmbxv7qcr
Closes https://github.com/apache/iceberg-python/issues/1121
=> Drop support for Python 3.8

pyiceberg/transforms.py
Follow-up from #1208, documents the conclusions from the discussion.
=> Add clarifying docs to transform result types

mkdocs/docs/configuration.md, pyiceberg/catalog/sql.py, tests/catalog/test_sql.py
Remove unnecessary _ensure_tables_exist method  as this is already the default behavior of Metadata.create_all()
=> Add flag to allow disabling creation of catalog tables

pyiceberg/cli/console.py, pyiceberg/table/__init__.py
I will be opening some PRs that will make it possible to implement the expire snapshot procedure. To make it easier to review, I'm breaking it down into smaller PRs.
=> Move snapshot history expire table properties to constants

pyiceberg/table/__init__.py, tests/integration/test_writes/test_writes.py
We have encountered a data loss issue when using pyIceberg to perform an overwrite operation. Typically, an overwrite operation involves creating both a delete snapshot and an append snapshot. However, if an exception occurs during the creation of the append snapshot, the current code still attempts to commit the delete snapshot, leading to potential data loss. One thing to note is this does not apply to only overwrite but potentially other operations as well.
To address this issue, we need to ensure that the entire transaction is aborted if any part of the update process fails.
Also provided a simple test case, where before this change, the transaction will only contains a delete snapshot update deleting the data. Whereas after this fix, we still keep the same data before the partially …
=> abort the whole table transaction if any updates in the transaction has failed

poetry.lock, pyproject.toml
=> Bump PyArrow to 18.0.0

pyiceberg/io/pyarrow.py
With Arrow 18.0.0 numpy is not a dependency anymore: https://github.com/apache/arrow/pull/44148
I think it would be good to remove it from PyIceberg.
Closes https://github.com/apache/iceberg-python/issues/1259
Closes https://github.com/apache/iceberg-python/issues/1198
=> Remove numpy as a hard dependency

pyiceberg/catalog/glue.py
This pull request addresses an issue where the list_tables function was returning views alongside Iceberg tables. Since views lack the table_type property or have it set differently than "iceberg", they were incorrectly included in the list of tables. This change modifies the filtering logic to ensure that only actual Iceberg tables are returned.
In the existing list_tables function, both Iceberg tables and Glue views were being returned. Glue views generally do not contain the table_type parameter or may have it unset, which causes them to be mistakenly included when listing Iceberg tables in a namespace. This behavior makes it challenging for users to retrieve only Iceberg tables as intended.
The __is_iceberg_table helper method has been modified to:
Check if the table_type parameter is …
=> fix: list_tables method in glue catalog now only return tables.

mkdocs/docs/configuration.md, pyiceberg/catalog/__init__.py, pyiceberg/catalog/dynamodb.py, pyiceberg/catalog/glue.py, pyiceberg/io/pyarrow.py, pyiceberg/table/__init__.py, tests/catalog/test_dynamodb.py, tests/catalog/test_glue.py, tests/conftest.py
Searching for `removed_in="0.8.0":
https://github.com/search?q=repo%3Aapache%2Ficeberg-python+removed_in%3D%220.8&type=code
Removed items:
* `DEPRECATED_PROPERTY_NAMES`
* `to_requested_schema` in `pyiceberg/io/pyarrow.py`
* `add_snapshot` and `set_ref_snapshot` in `pyiceberg/table/__init__.py`
=> Deprecate for 0.8.0 release

pyiceberg/catalog/rest.py, pyiceberg/table/__init__.py
See open-api spec:
https://github.com/apache/iceberg/blob/ea61ee46db17d94f22a5ef11fd913146557bdce7/open-api/rest-catalog-open-api.yaml#L927-L929
Resolves #1113
=> Pass table-token to commit endpoint

mkdocs/docs/configuration.md
=> Updating configuration docs

pyiceberg/expressions/parser.py, tests/expressions/test_parser.py
Currently, `row_filter` expressions involving a `boolean` expression fail. This pull adds in the already-defined boolean literals as part of the list of parsed literals. 
In addition, identifiers can now be defined with double quotes (`"`) as part of the SQL spec.
=> Add support for boolean expressions and quoted columns

mkdocs/docs/configuration.md, pyiceberg/catalog/__init__.py, pyiceberg/catalog/dynamodb.py, pyiceberg/catalog/glue.py, tests/catalog/test_dynamodb.py, tests/catalog/test_glue.py
Do not deprecate `botocore_session` in 0.8.0 release, due to #1104
Partial revert of #1269
Fixes https://github.com/apache/iceberg-python/issues/1104
=> Do not deprecate `botocore_session`

mkdocs/docs/how-to-release.md, mkdocs/docs/verify-release.md
Closes #1311
Deprecate the use of 
- https://dist.apache.org/repos/dist/dev/iceberg/KEYS
in favor of 
- https://downloads.apache.org/iceberg/KEYS which is an alias for https://dist.apache.org/repos/dist/release/iceberg/KEYS
devlist discussion: https://lists.apache.org/thread/8j41w4y2jx6r3ybj0o82bfyn0npmhgx2
=> use `dist/release` KEYS

dev/docker-compose-integration.yml, pyiceberg/catalog/rest.py, tests/catalog/test_rest.py
While testing out the iceberg-rest-catalog docker image, I ran into the following error when parsing the following example TableResponse that is created in `tests/integration/test_writes/test_writes.py::test_create_table_transaction[session_catalog-2]`
```
{'metadata': {'format-version': 2, 'table-uuid': 'f269bf0e-f8c9-4443-a341-e5bd4936892a', 'location': 's3://warehouse/default/arrow_create_table_transaction_local_2', 'last-sequence-number': 0, 'last-updated-ms': 1731553376222, 'last-column-id': 1, 'current-schema-id': 0, 'schemas': [{'type': 'struct', 'schema-id': 0, 'fields': [{'id': 1, 'name': 'foo', 'required': False, 'type': 'string'}]}], 'default-spec-id': 0, 'partition-specs': [{'spec-id': 0, 'fields': []}], 'last-partition-id': 999, 'default-sort-order-id': 0, 'sort-orders': …
```
=> Bug Fix: `metadata_location` to be optional in `TableResponse`

pyiceberg/catalog/rest.py
Closes #1318
`identifier_to_tuple_without_catalog` is deprecated, we should remove references of it from our codebase
=> use the non-deprecated func to parse identifier

.github/ISSUE_TEMPLATE/iceberg_bug_report.yml, dev/Dockerfile, pyiceberg/table/__init__.py
This PR addresses post-release steps as documented in https://py.iceberg.apache.org/how-to-release/ including
* Update the Github template
* Update the integration tests
This PR also fixes `Release the docs` since `mkdocs build --strict` fails https://github.com/apache/iceberg-python/actions/runs/11898959772/job/33156549032
=> 0.8.0 post release steps

pyiceberg/catalog/glue.py, pyiceberg/catalog/hive.py, tests/catalog/test_glue.py, tests/catalog/test_hive.py
=> Ignore tables without table_type parameters while loading all iceberg table from Glue and Hive catalog (#1331)

pyiceberg/table/sorting.py, tests/table/test_sorting.py
Fixes #1337 (nice)
Added a test to validate
=> Set default for `SortField`'s `transform` 

mkdocs/docs/configuration.md, pyiceberg/catalog/__init__.py, pyiceberg/catalog/glue.py, tests/catalog/test_glue.py
Configurable retry mechanism for the Glue catalog Boto client.
- Setting the retry mode to `standard`
- Introducing a new configuration `glue.max-retries` with default value set to 10
- Adding the new configuration key to the documentation
Closes #1294
=> Boto Glue standard retry policy with configuration

pyiceberg/utils/deprecated.py, pyproject.toml
When looking into #1346, I was confused by why the `datetime.datetime.utcfromtimestamp` warning only errored for the branch and not for the `main` branch. 
Turns out there's a bug in the `_deprecation_warning` code where **all warnings** are suppressed when displaying a deprecation warning. The `datetime.datetime.utcfromtimestamp` warning is suppressed in the `main` branch because the test also triggered other deprecation warnings. When those deprecation warnings are removed in the feature branch, the only other warning is shown and causes the test to fail. 
This PR changes `_deprecation_warning` to temporarily override warning handling.
=> dont override global warning

pyiceberg/catalog/glue.py, pyiceberg/catalog/hive.py, pyiceberg/catalog/rest.py, pyiceberg/catalog/sql.py, pyiceberg/cli/output.py, pyiceberg/table/__init__.py, pyproject.toml, tests/catalog/integration_test_dynamodb.py, tests/catalog/integration_test_glue.py, tests/catalog/test_base.py, tests/catalog/test_dynamodb.py, tests/catalog/test_glue.py, tests/catalog/test_hive.py, tests/catalog/test_rest.py, tests/catalog/test_sql.py, tests/integration/test_reads.py
Closes #1336, related to #1327
This PR changes the implementation of the `Table.name` function to use `self._identifier` instead of `self.identifier` to avoid having unnecessary deprecation warnings. 
This PR also replaces all references of `Table.identifier` with `Table.name()` to prepare for the deprecation of `Table.identifier` and avoid emitting warnings in tests. Using VSCode, I confirmed all use of `Table.identifier` is replaced in the repo.
=> Replace reference of `Table.identifier` with `Table.name`

pyiceberg/expressions/parser.py, tests/expressions/test_parser.py
=> Allow leading underscore in column name used in row filter

.github/workflows/python-ci-docs.yml, .github/workflows/python-release-docs.yml
This PR adds a new GitHub Action to run `mkdocs build --strict` for every PR.
* `python-ci-docs.yml` was previously used to release doc changes, it's copied over and renamed to `python-release-docs.yml`.
* `python-ci-docs.yml` now runs `mkdocs build --strict` for every PR.
When releasing docs, the `python-ci-docs.yml` GitHub Action uses `--strict`. This action is only triggered during the release process, which requires an ad-hoc fix, see #1334.
https://github.com/apache/iceberg-python/blob/7a83695330518bea0dee589b5b513297c4d59b66/.github/workflows/python-ci-docs.yml#L42
Lets make sure this is checked in new PRs
=> check mkdocs build strict in CI

mkdocs/docs/how-to-release.md
Closes #1306
Uploaded the documentation for "how to release" based on recent experience with releasing 0.8.0 (See [PyIceberg 0.8.0 release notes](https://docs.google.com/document/d/1gPG8pZKavUgd-Avj4Od8qJSP7fCd9ga6x6qVqaaDw1w/edit?usp=sharing))
Additional potential improvements
* Use `gh` command to trigger GitHub Actions and download artifacts (similar to [iceberg-go release script](https://github.com/apache/iceberg-go/blob/adc8193de3299b04c9763c2fba529a7b94d080ce/dev/release/release_rc.sh#L89-L96))
* Consider triggering `Python release` github action on tag push. Is it possible to run the release action once instead of twice (main + tag)?
=> Improve documentation for "how to release"

pyiceberg/io/pyarrow.py, tests/io/test_pyarrow_stats.py
Resolves #1353, by switching `del` with `pop` to prevent `KeyError`.
=> fix `KeyError` raised by `add_files` when parquet file doe not have column stats

mkdocs/docs/how-to-release.md
Clarify the use of `pyiceberg-0.8.x` branch and cherry-picking commits
=> Add instruction for patch release

pyiceberg/table/update/__init__.py
This should not be part of the public API: https://github.com/apache/iceberg/pull/11514
This PR depends on a later version of the REST catalog for the integration tests.
=> Deprecate the use of `last-column-id`

.github/workflows/python-release.yml
Both `actions/upload-artifact@v3` and `actions/download-artifact@v3` are deprecated and requires update, based on https://lists.apache.org/thread/nx19j3h61tjmsk8c8vx24gbq6ygf7pyf
`upload-artifact@v3` only used in iceberg-python
https://grep.app/search?q=actions/upload-artifact%40v3&filter[repo.pattern][0]=apache/iceberg
`download-artifact@v3` is not used in any iceberg-related repos
https://grep.app/search?q=actions/download-artifact&filter[repo.pattern][0]=apache/iceberg
Migrate from V3 to V4 following [the migration guide to merge multiple artifacts into one](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#merging-multiple-artifacts) with [`@actions/upload-artifact/merge`](https://github.com/actions/upload-artifact/blob/main/merge/README.md). 
Removed `macos-12` …
=> Update `upload-artifact` to use v4

pyiceberg/manifest.py, tests/utils/test_manifest.py
This follows the same as in Java, otherwise we'll write `None`
=> Write `null` when there is no parent-snapshot-id

.github/ISSUE_TEMPLATE/iceberg_bug_report.yml, dev/Dockerfile, mkdocs/docs/how-to-release.md, poetry.lock, pyiceberg/__init__.py, pyiceberg/catalog/glue.py, pyiceberg/catalog/hive.py, pyiceberg/catalog/rest.py, pyiceberg/catalog/sql.py, pyiceberg/cli/output.py, pyiceberg/expressions/parser.py, pyiceberg/io/pyarrow.py, pyiceberg/manifest.py, pyiceberg/table/__init__.py, pyproject.toml, tests/catalog/integration_test_dynamodb.py, tests/catalog/integration_test_glue.py, tests/catalog/test_base.py, tests/catalog/test_dynamodb.py, tests/catalog/test_glue.py, tests/catalog/test_hive.py, tests/catalog/test_rest.py, tests/catalog/test_sql.py, tests/expressions/test_parser.py, tests/integration/test_reads.py, tests/io/test_pyarrow_stats.py, tests/utils/test_manifest.py
[pyiceberg 0.8.1 proposal on devlist](https://lists.apache.org/thread/j4l5xk92j6z3pb31wyqtxk7fbf1621kv)
The behavior of `Table.name` is changed to return the table name **without the catalog name**. This is a broader effort to remove references to the catalog name in pyiceberg. 
* Replace usage of `Table.identifier` with `Table.name` which returns the table name without the catalog name
* Replace the use of a deprecated function (`identifier_to_tuple_without_catalog`) in pyiceberg; remove unnecessary warnings
Documentation updates are included to reflect the updated process in https://py.iceberg.apache.org/
* Update “how to release” documentation
* 0.8.0 post-release steps
Bug fixes
* Fix `add_files` for parquet files without column stats
* Allow leading underscore in column name used in …
=> [release] Pyiceberg 0.8.1

dev/Dockerfile
CI constantly fails because `curl` errors intermittently, up curl retry to `5`.
By default `--retry` uses exponential backoff. From the docs, https://curl.se/docs/manpage.html
```
By using [--retry-delay](https://curl.se/docs/manpage.html#--retry-delay) you disable this exponential backoff algorithm.
```
=> [INFRA] make integration test more resilient to intermittent failures 

dev/docker-compose-integration.yml, pyiceberg/catalog/rest.py, tests/catalog/test_rest.py, tests/integration/test_writes/test_writes.py
NOTE: the test is failing because tableExists endpoint isn't exposed on the adapter. Related fix: https://github.com/apache/iceberg/pull/11678
=> TEST: adopt new rest catalog image and enable tableExists tests

poetry.lock, pyproject.toml, tests/integration/test_reads.py
Closes #1409
This PR updates the following packages, (using `poetry update <package>`):
- pandas `2.0.3` -> `2.2.3` (#1282)
- getdaft `0.3.14` -> `0.3.15` (#1397)
Fixed warning for daft, allow listed warning for pyspark.
=> fix warnings from newer versions of dependencies

.github/ISSUE_TEMPLATE/iceberg_bug_report.yml, dev/Dockerfile
Post-release steps for 0.8.1 release https://py.iceberg.apache.org/how-to-release/#post-release
Similar to #1334
=> 0.8.1 post release

pyiceberg/transforms.py, tests/test_transforms.py
This aligns more closely with Java, and is also easier to read.
=> Update StrictProjection tests

pyiceberg/types.py, tests/conftest.py, tests/test_schema.py
Ensures that these attributes are correctly applied to the NestedField when reading an Iceberg schema json file.
Fixes #1431
=> Deserialize NestedField initial-default and write-default Attributes

pyiceberg/catalog/__init__.py, pyiceberg/cli/output.py, pyiceberg/table/snapshots.py, tests/conftest.py, tests/table/test_metadata.py
Since we don't support `manifests`, we can assume that the manifest-list is there all the time.
=> Snapshot: Make manifest-list required

pyiceberg/catalog/rest.py, tests/catalog/test_rest.py, tests/integration/test_rest_catalog.py
As per #1430  I have added the namespace_exists functionality for REST Catalog.
Here's an example usage similar to the table_exists function of the same class 
Please review the changes
=> Implementing namespace_exists function on the REST Catalog

dev/docker-compose-azurite.yml, dev/docker-compose-gcs-server.yml, dev/docker-compose-integration.yml, dev/docker-compose.yml
Seeing this in the logs:
```
time="2024-12-09T14:41:56Z" level=warning msg="/home/runner/work/iceberg-python/iceberg-python/dev/docker-compose-gcs-server.yml: `version` is obsolete"
```
Less is more!
=> Remove `version` from `docker-compose`

pyiceberg/table/name_mapping.py, tests/table/test_name_mapping.py
=> fix: field id in name mapping should be optional

mkdocs/docs/configuration.md
=> [DOCS] Add RESTCatalog-specific headers table

pyiceberg/catalog/__init__.py, pyiceberg/catalog/dynamodb.py, pyiceberg/catalog/glue.py, pyiceberg/catalog/hive.py, pyiceberg/catalog/rest.py, pyiceberg/catalog/sql.py, pyiceberg/table/__init__.py, tests/catalog/test_base.py, tests/catalog/test_sql.py
Currently, we optionally support catalog names being specified in the identifier string. In other words, this means that we currently support identifier names that look like `catalog_name.table_namespace.table_name` or `table_namespace.table_name` being passed into `catalog.load_table()` method.
This PR proposes to remove this optional support, and change the `Table` class's identifier to be `(table_namespace, table_name)` instead of `(catalog_name, table_namespace, table_name)`. The reasons are as follows:
1. The Identifier is specified as namespace + table_name according to the [REST Catalog Open API Spec](https://github.com/apache/iceberg/blob/3495d9edaee30c1714a810eb35635f8be20fc106/open-api/rest-catalog-open-api.yaml#L1657)
2. `Table` has the attribute `catalog` - a Table is always …
=> Remove support for catalog_name in table identifier string

dev/provision.py
Speeds up the integration tests
=> Remove unneeded partitioning

dev/Dockerfile, tests/conftest.py, tests/integration/test_deletes.py
Integration test dockerfile is using version `1.6.0`
https://github.com/apache/iceberg-python/blob/325c8a55d455e479813bdfa831c450991f9c4d36/dev/Dockerfile#L39-L41
Also fixed tests since https://github.com/apache/iceberg/issues/10122 is fixed in new versions
We should figure out a way to keep this in sync.
=> [infra] Update pyspark java iceberg library to 1.6.0

mkdocs/docs/api.md, mkdocs/docs/how-to-release.md, mkdocs/docs/verify-release.md, pyiceberg/table/__init__.py, pyiceberg/utils/decimal.py, tests/integration/test_writes/test_partitioned_writes.py, tests/table/test_init.py
Corrects a few minor spelling issues where I used [codespell](https://github.com/codespell-project/codespell). 
There are still some typos present, but they are mostly in tests, and many of them are abbreviations I suspect would need to be kept, such as:
BoundIn ==> bounding
NotIn ==> noting, not in, notion
nd ==> and, 2nd
mis ==> miss, mist
re-use ==> reuse
notIn ==> noting, not in, notion
fo ==> of, for, to, do, go
hel ==> help, hell, heal
MoR ==> more
oT ==> to, of, or, not, it
=> docs: various spelling fixes

pyiceberg/partitioning.py, tests/integration/test_partitioning_key.py, tests/table/test_partitioning.py
=> URL-encode partition field names in file locations

.codespellrc, .pre-commit-config.yaml, mkdocs/docs/api.md, mkdocs/docs/how-to-release.md, mkdocs/docs/verify-release.md, pyiceberg/avro/reader.py, pyiceberg/io/pyarrow.py, pyiceberg/table/__init__.py, pyiceberg/utils/decimal.py, pyiceberg/utils/singleton.py, tests/integration/test_writes/test_partitioned_writes.py, tests/table/test_init.py, tests/test_transforms.py
Following up with https://github.com/apache/iceberg-python/pull/1471 to detect spelling issues with pre-commit. 
I went with adding a `.codespellrc` file to store the `ignore-words-list.` I think it's possible to configure this in the `pyproject.toml` as well. We could probably swap that out if desired.
=> ci: configure codespell in pre-commit

pyiceberg/utils/deprecated.py, tests/catalog/test_rest.py, tests/expressions/test_parser.py
Removing deprecation warnings emitted during pytests. This will also prepare us for `0.9.0` release
Fix these errors in `make-test`:
* `tests/catalog/test_rest.py`
`Deprecated in 0.8.0, will be removed in 1.0.0. Iceberg REST client is missing the OAuth2 server URI configuration`
* `tests/expressions/test_parser.py::test_is_null`
`Deprecated in 0.8.0, will be removed in 0.9.0. Parsing expressions with table name is deprecated. Only provide field names in the row_filter.`
=> Remove deprecation warnings in test

mkdocs/docs/api.md, pyiceberg/partitioning.py, tests/integration/test_partitioning_key.py
Follow-up to #1457 that addresses nits on that PR.
=> Nit fixes to URL-encoding of partition field names

tests/table/test_locations.py
See https://github.com/apache/iceberg-python/pull/1509#issuecomment-2585391350 for context/motivation.
This PR better highlights location provider behaviour in the presence of partitions in unit tests. It tests related behaviour more carefully - e.g. it tests that partition values **and** entropy included in paths when object storage location provision is used (without partitioned paths disabled) that can be confusing. It also tests the injected hash itself in this scenario because it's the hash method of *both* the file name and the partition key - this matches the Java implementation and I've tested that the Java code produces the same output for this case (https://github.com/apache/iceberg/blob/main/core/src/test/java/org/apache/iceberg/TestLocationProvider.java has no tests for this …
=> Improve `LocationProvider` unit tests

pyiceberg/manifest.py
Modified the FileFormat class so that it utilizes EnumMeta value aliases.
This allows specifying both "AVRO" and "avro" to map to AVRO, for example.
This addresses Issue #1340
Closes #1340
=> Added support for lowercase FileFormat for Issue #1340

pyiceberg/io/__init__.py, pyiceberg/io/fsspec.py, pyiceberg/io/pyarrow.py
=> IO: Remove deprecations

dev/Dockerfile
Use `archive.apache.org` to download Spark since version `3.5.3` has been removed from https://dlcdn.apache.org/spark/
, replaced with the latest patch `3.5.4`. I guess this will happen on every patch release. 
We can't upgrade to `3.5.4` yet per this comment https://github.com/apache/iceberg-python/pull/1461#issuecomment-2572498850. This will be unblocked with the upcoming 1.7.2 release. 
Note, this PR essentially reverts the work done in #1425 but will unblock CI
=> [infra] download Spark from `archive.apache.org`

.pre-commit-config.yaml
This check gives false positives on attribute docstrings with warnings
such as:
- "Multiple module docstrings (first docstring on line N)", or
- "Module docstring appears after code (code seen on line N)"
For details, see:
https://github.com/pre-commit/pre-commit-hooks/issues/159
=> fix: remove check-docstring-first pre-commit check

pyiceberg/partitioning.py, pyiceberg/table/metadata.py, pyiceberg/table/sorting.py, pyiceberg/typedef.py, tests/conftest.py, tests/table/test_metadata.py, tests/table/test_partitioning.py, tests/table/test_sorting.py
=> Add V3 read support

pyiceberg/exceptions.py, pyiceberg/io/pyarrow.py, tests/integration/test_add_files.py, tests/io/test_pyarrow_visitor.py
This modifies the exception being thrown when converting PyArrow types to Iceberg types, it also now declares the field being involved, if applicable, and can also be accessed when catching the exception.
closes #860
=> Modified exception objects being thrown when converting Pyarrow tables

pyiceberg/expressions/literals.py, pyiceberg/typedef.py, tests/expressions/test_literals.py, tests/integration/test_reads.py
Support `datetime` objects being passed into the `literal` function.
Allows situations like the following: 
```py
from datetime import datetime
...
row_filter=And(
GreaterThanOrEqual("my_timestamp_column", datetime.now()),
),
```
Which previously failed
Closes #1456
=> feat: support datetime objects in literal instantiation

pyiceberg/transforms.py, tests/table/test_partitioning.py
I think this aligns closer to the spec, and is also more friendly to the end-user:
=> Refactor `bucket` transform types

pyiceberg/typedef.py
This allows mkdocstrings to generate hyperlinks
to these types in the documentation.
Fixes: #1529
=> docs: Add docstrings for Identifier, Properties, RecursiveDict

tests/integration/test_partitioning_key.py
Following up #1555, which commented out tests in `tests/integration/test_partitioning_key.py`
This PR uncomment those tests; they can run succesfully
=> follow up #1555, bring back tests

pyiceberg/table/update/__init__.py, pyiceberg/table/update/statistics.py, tests/integration/test_statistics_operations.py, tests/table/test_init.py
=> Remove redundant snapshot_id from SetStatisticsUpdate

pyiceberg/table/inspect.py
Fixes: https://github.com/apache/iceberg-python/issues/1574
Demo (redacted):
```
>>> table.inspect.entries()
pyarrow.Table
status: int8 not null
snapshot_id: int64 not null
sequence_number: int64 not null
file_sequence_number: int64 not null
data_file: struct<content: int8 not null, file_path: string not null, file_format: string not null, partition: struct<> not null, record_count: int64 not null, file_size_in_bytes: int64 not null, column_sizes: map<int32, int64>, value_counts: map<int32, int64>, null_value_counts: map<int32, int64>, nan_value_counts: map<int32, int64>, lower_bounds: map<int32, binary>, upper_bounds: map<int32, binary>, key_metadata: binary, split_offsets: list<item: int64>, equality_ids: list<item: int32>, sort_order_id: int32> not null
child 0, content: int8 not null …
```
=> Return an empty dict if nan values is not provided by the catalog

pyiceberg/catalog/__init__.py, pyiceberg/io/__init__.py, pyiceberg/table/locations.py, tests/io/test_io.py, tests/table/test_locations.py
Closes #1577.
Log the underlying exception when a FileIO import fails.
=> Log exception when FileIO import fails

mkdocs/docs/contributing.md
Closes #970
This PR links community guideline on contribution, https://iceberg.apache.org/contribute/
=> [docs] Link community contributing guidelines

pyiceberg/partitioning.py, pyiceberg/table/metadata.py, pyiceberg/table/refs.py, pyiceberg/table/sorting.py, pyiceberg/table/update/__init__.py, tests/test_transforms.py
`Annotated` has been part of `typing` since 3.9
=> Move from `types_extensions` to `types`

tests/table/test_partitioning.py
I like this test from #1562, lets expand it to include all transforms
=> Test transform function consistency for all transforms

pyiceberg/table/metadata.py
Missed this in https://github.com/apache/iceberg-python/pull/1554
=> Update annotation with V3

.github/workflows/pypi-build-artifacts.yml, .github/workflows/python-release.yml, .github/workflows/svn-build-artifacts.yml
Moved `svn-build-artifacts` and `svn-merge-artifacts` into `.github/workflows/svn-build-artifacts.yml`
Moved `pypi-build-artifacts` and `pypi-merge-artifacts` into `.github/workflows/pypi-build-artifacts.yml`
Test run: https://github.com/kevinjqliu/iceberg-python/actions/runs/13102665689
Still generates the same artifacts
* `svn-release-candidate-${VERSION}rc${RC}` for SVN
* `pypi-release-candidate-${VERSION}rc${RC}` for PyPi
This is so can run pypi artifacts nightly.
=> [infra] refactor release github workflow

.github/dependabot.yml
Bump dependabot open PR limit to 50, similar to [iceberg-rust/#921](https://github.com/apache/iceberg-rust/pull/921)
=> [infra] bump dependabot open PR limit

.github/workflows/pypi-build-artifacts.yml, .github/workflows/svn-build-artifacts.yml
Removes `CIBW_TEST_EXTRAS: "s3fs,glue" since we dont need the extra dependencies for tests 
Removes skipping MacOS build in `CIBW_TEST_SKIP`
Test run on fork of release candidate on https://github.com/kevinjqliu/iceberg-python/actions/runs/13117565428
=> [infra] clean up cibuildwheel build

.github/workflows/nightly-pypi-build.yml, .github/workflows/pypi-build-artifacts.yml, .github/workflows/python-release.yml, .github/workflows/svn-build-artifacts.yml, pyproject.toml
Closes #872
This PR adds the ability to run and publish pypi artifacts nightly to testpypi. It will publish as `pyiceberg` with new version under `0.9.0.dev${TIMESTAMP}`, i.e. `0.9.0.dev20250206050843`, adhering to PEP440 conversion.
Here's a [test run on my fork](https://github.com/kevinjqliu/iceberg-python/actions/runs/13172235318) which published to https://test.pypi.org/project/pyiceberg-kevinliu/
This requires setting up [Publishing to PyPI with a Trusted Publisher](https://docs.pypi.org/trusted-publishers/) on https://test.pypi.org/ and using example of publishing [pyiceberg_core](https://github.com/apache/iceberg-rust/blob/8714ffd69c411990a89e1c3f03b51c33670f18ec/.github/workflows/release_python.yml#L120-L146) to testpypi
Note, this PR also refactors …
=> [infra] add testpypi nightly build 

pyiceberg/io/fsspec.py
In case you don't have `botocore` installed.
=> fsspec: Remove `botocore` as a module import

pyiceberg/table/__init__.py
=> fix new requirements handling

pyiceberg/io/pyarrow.py, tests/io/test_pyarrow.py
This is a fix for issue #1401. In which table scans needed to infer partition column by following the column projection [rules](https://iceberg.apache.org/spec/#column-projection)
Fixes https://github.com/apache/iceberg-python/issues/1401
=> Implement column projection 

pyiceberg/table/locations.py
Sometime I'm seeing this:
```
ImportError while loading conftest '/home/runner/work/iceberg-python/iceberg-python/tests/conftest.py'.
tests/conftest.py:52: in <module>
from pyiceberg.catalog import Catalog, load_catalog
pyiceberg/catalog/__init__.py:51: in <module>
from pyiceberg.serializers import ToOutputFile
pyiceberg/serializers.py:25: in <module>
from pyiceberg.table.metadata import TableMetadata, TableMetadataUtil
pyiceberg/table/__init__.py:65: in <module>
from pyiceberg.io.pyarrow import ArrowScan, schema_to_pyarrow
pyiceberg/io/pyarrow.py:141: in <module>
from pyiceberg.table.locations import load_location_provider
pyiceberg/table/locations.py:25: in <module>
from pyiceberg.table import TableProperties
E   ImportError: cannot import name 'TableProperties' from partially …
```
=> Break circular import

.asf.yaml
We just had an issue with merging a stale branch, which fixed @kevinjqliu right away in https://github.com/apache/iceberg-python/pull/1638
In `iceberg-rust` they have this nice button:
I think this is the result of the following config:
https://github.com/apache/iceberg-rust/blob/63545895d2c35db0f0c550cb1c08acd52a9f5b4c/.asf.yaml#L36C10-L39C21
I don't think it would work well for Java because of the activity there, and the time it takes to run the Spark integration tests, but I would love to have this button here.
=> Repo: Set status checks to strict

mkdocs/docs/api.md, mkdocs/docs/cli.md, mkdocs/docs/configuration.md, pyiceberg/utils/config.py, tests/utils/test_config.py
Resolves #1333 
Adds the current working directory to the search path for the `.pyiceberg.yaml` file. 
As it is now, the file is searched in the following order:
1. the `PYICEBERG_HOME` environment variable
2. ~/
3. ./
I'm unsure if people would like to have 2 and 3 swapped. In either case, users can still override this with the environment variable.
=> feat: search current working directory for config file

Makefile
make install should use the correct poetry version
Previously, make install just check if `poetry` was installed and might run with an older version. This would lead to a lot of changes in the poetry.lock file and merge conflicts for other PRs
=> [infra] update poetry if necessary

mkdocs/docs/configuration.md, pyiceberg/catalog/__init__.py, pyiceberg/catalog/dynamodb.py, pyiceberg/catalog/sql.py, pyiceberg/table/__init__.py, pyiceberg/table/locations.py, pyiceberg/table/update/snapshot.py, tests/catalog/test_base.py, tests/table/test_locations.py
Adding support for writing metadata to a custom path set via `write.metadata.path` property. Since the Python library consolidates the table operation classes in both the table and catalog classes, I had to surface the metadata file location handling to the base `Catalog` class to avoid circular dependencies. This way we are also able to centralize the metadata location handling for table metadata and snapshots. 
Relates to #1492
=> Add support for `write.metadata.path`

pyiceberg/table/update/__init__.py, pyiceberg/table/update/snapshot.py, tests/integration/test_snapshot_operations.py, tests/table/test_init.py
Part of https://github.com/apache/iceberg-python/pull/1561
Closes https://github.com/apache/iceberg-python/pull/822
=> Implement update for `remove-snapshot-ref` action

mkdocs/docs/api.md, pyiceberg/table/__init__.py, tests/table/test_upsert.py
And make the join-cols optional using the identifier fields.
=> Add upsert docs

mkdocs/docs/SUMMARY.md, mkdocs/docs/nightly-build.md
Nightly testpypi build was added in #1601
This PR adds a subpage under "Releases" about the nightly build.
Running `make docs-serve` locally,
=> [docs] add docs about nightly build

pyiceberg/catalog/sql.py, tests/catalog/test_sql.py
Resolves #1630
Links to Java implementation:
- https://github.com/apache/iceberg/blob/bcbbd0344623ffea5b092e2de5debb0bc12892a1/core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java#L788-L806
- https://github.com/apache/iceberg/blob/bcbbd0344623ffea5b092e2de5debb0bc12892a1/core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java#L331
- https://github.com/apache/iceberg/blob/bcbbd0344623ffea5b092e2de5debb0bc12892a1/core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java#L422
=> fix: SqlCatalog namespace_exists should work with multi-level namespaces

pyiceberg/table/__init__.py
Hello!
I have noticed the same issue as Issue #1506 where the number of results retrieved is inconsistent across reads and traced the issue to the reuse of the same metrics evaluator across threads when reading manifests. Because the metrics evaluator is stateful, this will result in the wrong results being retrieved nondeterministically, depending on the execution order of the threads. 
This PR addresses the issue by creating a single metrics evaluator per thread, which I have tested locally. Please let me know if there are any tests I can add, and I am happy to receive feedback.
Thank you!
Closes #1506
=> [Bug Fix] Avoid reusing shared metrics evaluator across threads

pyiceberg/expressions/parser.py, tests/expressions/test_expressions.py, tests/expressions/test_parser.py
This PR deprecates one of the three items that were planned for the 0.9.0 release. 
All items marked for removal:
<https://github.com/apache/iceberg-python/blob/efc8b5ac0f16717f776e034ecf9a9e9bdabd8424/pyiceberg/expressions/parser.py#L95>
<https://github.com/apache/iceberg-python/blob/efc8b5ac0f16717f776e034ecf9a9e9bdabd8424/pyiceberg/catalog/rest.py#L324>
<https://github.com/apache/iceberg-python/blob/efc8b5ac0f16717f776e034ecf9a9e9bdabd8424/pyiceberg/catalog/__init__.py#L790>
Currently there are three items marked for release. However, based on the ongoing [discussion](https://lists.apache.org/thread/rr8lcf96jl6079dz6vfkwr5spbvlxzpm), it appears that the other two items. have not yet been replaced with a proper solution. As a result, this PR only addresses the deprecation of `Table name …
=> Remove parsing table name in `row_filter`

pyiceberg/table/__init__.py, pyiceberg/table/upsert_util.py, tests/table/test_upsert.py
When you upsert into an empty table, it fails because it tries to search for records to be updated 🤔
=> Allow upserting into an empty table

pyiceberg/expressions/__init__.py, tests/expressions/test_expressions.py
I got inspired by Arrow that also allows for this.
=> Add syntactic sugar for `and` and `or` operation

pyiceberg/table/__init__.py
The [release candidate artifact build environment](https://github.com/apache/iceberg-python/blob/a58f099aa501f6fd4345a331295d81fe0133554f/.github/workflows/pypi-build-artifacts.yml#L72-L74) does not automatically install `pyarrow`. So when the import requires `pyarrow`, it fails. See run https://github.com/apache/iceberg-python/actions/runs/13464626812/job/37627644985
Import is via `conftest`
```
ImportError while loading conftest '/project/tests/conftest.py'.
/project/tests/conftest.py:52: in <module>
from pyiceberg.catalog import Catalog, load_catalog
../venv/lib/python3.9/site-packages/pyiceberg/catalog/__init__.py:51: in <module>
from pyiceberg.serializers import ToOutputFile
../venv/lib/python3.9/site-packages/pyiceberg/serializers.py:25: in <module>
from pyiceberg.table.metadata …
```
=> Remove top-level import of `pyarrow`

pyiceberg/table/upsert_util.py
Now we have the syntactic sugar (https://github.com/apache/iceberg-python/pull/1697), we don't need Lambda's anymore and can use the `operator.{and_,or_}` functions.
Also, the reduce is okay with just having a single argument, while `And(*[EqualTo('a', 22)])` would fail.
```
python3
Python 3.10.14 (main, Mar 19 2024, 21:46:16) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import functools
>>> functools.reduce(lambda a, b: a + b, [1])
1
>>> functools.reduce(lambda a, b: a + b, [1, 2])
3
```
=> Upsert: Align codestyle

pyiceberg/table/__init__.py, tests/integration/test_writes/test_partitioned_writes.py, tests/table/test_locations.py
Closes #1721
Otherwise, there's a default behavior change in new 0.9.0 release. Previous versions will write to `data/`, new version will write to `data/<hash>/`
=> Turn `ObjectStoreLocationProvider` off by default

mkdocs/docs/configuration.md
Update the docs to reflect the simple location provider as the default location provider.
related to #1721, and #1722.
cc: @kevinjqliu
=> Update docs to reflect default location provider

pyiceberg/table/__init__.py
=> Remove unused argument

pyiceberg/io/pyarrow.py, pyiceberg/table/__init__.py, tests/integration/test_add_files.py
- `parquet_files_to_data_files` changed to `parquet_file_to_data_files` which processes a single parquet file and returns a `DataFile`
- `_parquet_files_to_data_files` uses internal ExecutorFactory
resolves https://github.com/apache/iceberg-python/issues/1335
=> parallelize `add_files`

pyiceberg/catalog/rest.py, tests/catalog/test_rest.py
This is a follow up item from a recent discussion on the mailing list[1], where the community decided that 401 response should be preferred over 419 response on token expiry.
[1] mailing list discussion: https://lists.apache.org/thread/443skhqr59j3fj0ovg4tyxh9d4f4gysc
[2] REST Catalog Spec update PR: https://github.com/apache/iceberg/pull/12376
=> Fix: REST Catalog should retry on 401 status code

pyiceberg/io/pyarrow.py, tests/io/test_pyarrow_visitor.py
=> Support `string_view` and `binary_view`

pyiceberg/io/fsspec.py
We observed that the property with token returned by Polaris is `adls.sas-token.<account name>` and the extra condition causes is to be ignored
=> fix adlss properties processing

tests/conftest.py
For the tests, we want to limit parallelism to avoid creating 1-row Parquet files.
=> CI: Limit parallelism

pyiceberg/catalog/sql.py, tests/catalog/test_base.py, tests/catalog/test_sql.py
Resolves: https://github.com/apache/iceberg-python/issues/1627
=> Fix: `SqlCatalog` list_namespaces() should return only sub-namespaces

pyiceberg/transforms.py, tests/test_transforms.py
Follow up of https://github.com/apache/iceberg-rust/pull/946/. Looking at Java, this should be fine:
- String: https://github.com/apache/iceberg/blob/19330fa19f833f481063704c1e0122e068289259/api/src/main/java/org/apache/iceberg/transforms/Truncate.java#L364-L365
- Binary: https://github.com/apache/iceberg/blob/19330fa19f833f481063704c1e0122e068289259/api/src/main/java/org/apache/iceberg/transforms/Truncate.java#L445-L446
=> Fix strict projection for `string` and `binary`

.github/pull_request_template.md, dev/.rat-excludes, mkdocs/docs/how-to-release.md
While @kevinjqliu did an amazing job summarizing the new stuff in 0.9.0 in the GitHub release (https://github.com/apache/iceberg-python/releases/tag/pyiceberg-0.9.0), I think it would be good to formalize this a bit.
This also came up in https://github.com/apache/iceberg-python/pull/1669 where we introduced a behavioral change. cc @sungwy 
I think it would be good to allow users to populate the changelog section to ensure they know about any relevant changes.
The template is pretty minimal now to avoid being a big barrier to opening a PR.
=> Add pull-request template

pyiceberg/table/inspect.py, tests/integration/test_inspect_table.py
While doing some checks, I've noticed that these are missing.
=> Include DELETE entries when inspecting

pyiceberg/table/__init__.py, tests/table/test_upsert.py
Yikes! This makes sure to only produce a snapshot when there is anything to update or append.
Yes, by checking the snapshots that are being produced.
Smaller metadata and faster commits when there is nothing to append/update :)
=> Upsert: Don't produce empty snapshots

pyiceberg/conversions.py, tests/test_conversions.py
Adds support for encoding built-in Python values into JSON encoded values, according to the spec: https://iceberg.apache.org/spec/#json-single-value-serialization
Yes, with both expected/actual and round-trip tests.
No
=> Add JSON single value encoding

dev/provision.py, pyiceberg/schema.py, tests/expressions/test_expressions.py, tests/integration/test_reads.py, tests/test_schema.py
Closes #1778.
Current, filters that are applied to the top-level struct column do not work. For example, given a table of schema:
```
table {
2: id: optional int
1: data: required string
3: location: struct<5: latitude: optional float, 6: longitude: optional float>
}
```
We want to support applying filters to field `location`, such as `location is not null`. Note that filters like `location == {"latitude": ..., "longitude": ...}` wont work right now, but can be equivalently rewritten to `location.latitude == ... and location.longitude == ...`. 
Yes, tests were added at both the schema level and table reads.
Support some basic filters on struct columns at the top-level.
=> Support Filters on Top-Level Struct Fields

tests/conftest.py
=> nit: Clean up import in `conftest.py`

.github/dependabot.yml
Closes #1815
We have a lot of dependabot commits (in the 0.9.0 release, 148 commits were from contributors and 95 from Dependabot)
Dependabot config doc https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#required-keys
yes
no
=> [infra] run dependabot check weekly

pyiceberg/types.py, tests/test_types.py
Closes #1851
test_types.py
N/A
=> Pass data type as string representation to `NestedField`

pyiceberg/table/upsert_util.py, tests/table/test_upsert.py
Closes #1835
Original implementation, `!=` ([not_equal](https://arrow.apache.org/docs/python/generated/pyarrow.compute.not_equal.html#pyarrow.compute.not_equal)) does not account for `null` values. It emits `null` when either sides are `null`
The new implementation, first checks for `not_equal`. And on null values, returns `true` only if both sides are `null`
Similar to https://github.com/apache/iceberg-rust/pull/1045
Yes
No
=> fix `upsert` with null values

pyiceberg/io/pyarrow.py, tests/integration/test_writes/test_writes.py
=> Set field-id when needed

pyiceberg/transforms.py
When using pydantic>=2.11.0, we get an error when creating bucket transforms. In this version, it's illegal to access self before calling super. To fix this, we just need to ensure we call `super().__init__` before setting field properties on `self`.
---
Using `pydantic==2.11.0` the test `test_transforms.py::test_bucket_hash_values` fails
```python
tests/test_transforms.py:None (tests/test_transforms.py)
test_transforms.py:179: in <module>
(BucketTransform(2).transform(IntegerType()), 0, 0),
../pyiceberg/transforms.py:237: in __init__
self._num_buckets = num_buckets
../../../miniforge3/envs/pyiceberg/lib/python3.12/site-packages/pydantic/main.py:991: in __setattr__
setattr_handler(self, name, value)  # call here to not memo on possibly unknown fields …
```
=> Fix creation of Bucket Transforms with pydantic>=2.11.0

pyiceberg/table/__init__.py, tests/integration/test_statistics_operations.py
Addd a new API `Transaction.update_statistics()` to use the existing transaction instead of a brand new one.
I extended `tests/integration/test_statistics_operations.py::test_manage_statistics` to test the new API.
Users can now update statistics files within an ongoing transaction.
=> Add support for `Transaction.update_statistics()`

pyiceberg/expressions/parser.py, tests/expressions/test_parser.py
Our data lake uses old-school Kimball style quoted column names ("User ID", "Customer Name" etc). The string parser for `row_filter` was unable to parse this. Now it is. 
example: 
```python
>> parser.parse(' "User Name" = 'ted')
ParseException: Expected '"', found ' '
>> parser.parse(' "User Name" = 'ted')
EqualTo("User Name", "ted")
Yes a new test was added. 
```
>[!NOTE]
> The `quoted_column_with_dots` previously errored `with "Expected '"', found '.'"` _when using **double quotes only**_. It now raises error text expecting an `'or'` value; I didn't toil over finding where the exception is clobbered, because the error message between single and double quote exceptions is inconsistent and I didn't really consider this a polished/first-class error message. If this change is an issue, I …
=> Support quoted column identifiers for scan `row_filter` string argument

dev/Dockerfile
With https://github.com/apache/iceberg/pull/12593/ Row lineage is required and Spark uses Java 1.8.0 that does not write the required `first-row-id` field in the snapshot.
Therefore, I think it would be good to just use the SNAPSHOT for now until it gets released. We can easily revert the PR once that's done.
Closes #1898
=> CI: Use Java 1.9.0-SNAPSHOT for testing

pyiceberg/io/pyarrow.py, tests/integration/test_add_files.py
Found out I broke this myself after doing a `git bisect`:
```
36d383dcb676ae5ef59c34cc2910d16a8e30a80c is the first bad commit
commit 36d383dcb676ae5ef59c34cc2910d16a8e30a80c
Author: Fokko Driesprong <fokko@apache.org>
Date:   Thu Jan 23 07:50:54 2025 +0100
PyArrow: Avoid buffer-overflow by avoid doing a sort (#1555)
Second attempt of https://github.com/apache/iceberg-python/pull/1539
This was already being discussed back here:
https://github.com/apache/iceberg-python/issues/208#issuecomment-1889891973
This PR changes from doing a sort, and then a single pass over the table
to the approach where we determine the unique partition tuples filter on
them individually.
Fixes https://github.com/apache/iceberg-python/issues/1491
Because the sort caused buffers to be joined where it would …
```
=> Fix `add_files` with non-identity transforms

pyiceberg/catalog/hive.py
Closes #1744
`TSaslClientTransport` cannot be reopen. This PR changes the behavior to recreate a `TSaslClientTransport` when its already closed. 
Note, `_HiveClient` should be used with context manager, but can be used without.
=> Fix thrift client connection for Kerberos Hive Client 

tests/integration/test_writes/test_writes.py
Issue is fixed upstream, https://github.com/duckdb/duckdb-iceberg/issues/185
This reverts commit eb8756a00311955c6bea7ee3cc02320e58965293. (#1918)
=> Revert ignore duckdb test

mkdocs/docs/api.md, pyiceberg/table/__init__.py, tests/conftest.py, tests/table/test_init.py
This change allow making use of the `version-hint.text` file when a static table is instantiated with a `metadata_location` not ending with '.metadata.json'.
User can just point to the table location, and metadata file path will be read from `version-hint.text`.
Closes #763
`version-hint.text` is useful in context where you does not want or need a full-fledge catalog.
Our use case is sharing datasets publicly as Iceberg tables on S3.
No yet.
Yes. User can now points `StaticTable` to the table location rather than a specific version file.
=> Use version-hint.text for StaticTable 

pyiceberg/table/__init__.py, pyiceberg/table/update/__init__.py, tests/integration/test_rest_schema.py, tests/integration/test_writes/test_writes.py
Today, we have a copy of the `TableMetadata` on the `Table` and the `Transaction`. This PR changes that logic to re-use the one on the table, and add the changes to the one on the `Transaction`.
This also allows us to stack changes, for example, to first change a schema, and then write data with the new schema right away.
Also a prerequisite for https://github.com/apache/iceberg-python/pull/1772
Includes a new test :)
=> Refactor `Metadata` in `Transaction`

pyiceberg/table/update/spec.py, pyiceberg/transforms.py, tests/integration/test_partition_evolution.py
Closes #1882
Feature request: Ability to pass transform name as string in `add_fields`
Yes
Yes. Users will be able to pass transform names as string while calling add_fields method of update_spec.
=> Changes to support string transform in add_field.

pyiceberg/catalog/glue.py, tests/catalog/test_glue.py
Closes #1910 
When working with the GlueCatalog, I may already have a GlueClient that I've instantiated from elsewhere, and perhaps wish to keep. This allows passing our client to the GlueCatalog constructor so that we aren't forced into getting a new client.
This is slightly interesting because it's the only catalog that now has a different constructor signature. Also it may be odd for users to pass a client, but then none of their properties (which may have retry configs) are applied.
An alternative to consider is having a `from_client` or `with_client` staticmethod, but I did not see precedence elsewhere. I will leave it to the maintainers to decide which they prefer and will update accordingly. Similarly, I can do the same for dynamodb 🙂 
I've also skipped the event_handler for a …
=> Adds support for creating a GlueCatalog with own client

.github/workflows/python-ci.yml, .github/workflows/python-integration.yml, poetry.lock, pyiceberg/catalog/hive.py, pyproject.toml, tests/catalog/test_hive.py
Closes #1744 (second try) 
First try (#1747) did not fully resolve the issue. See https://github.com/apache/iceberg-python/pull/1747#pullrequestreview-2781186390
yes
=> Fix kerberized hive client

Makefile
[`poetry.lock` file](https://github.com/apache/iceberg-python/blob/59742e01e8d190aa759e0154b03300bd81a28d02/poetry.lock#L1) is generated with poetry 2.1.1
I suspect this is from dependabot. I couldn't find a way to control the version of poetry dependabot uses, so let's just match the version its using.
This way updating the lock file locally wont create a bunch of unrelated changed
=> [infra] update poetry to v2.1.1

pyiceberg/table/snapshots.py, pyiceberg/table/update/validate.py, tests/table/test_snapshots.py, tests/table/test_validate.py
Nit: the current order (`to_snapshot` before `from_snapshot`) is unexpected and [error-prone](https://github.com/apache/iceberg-python/pull/1938/files#r2070985497).
This PR proposes to reorder these parameters in `validation_history` and `ancestors_between` so that it is more idiomatic.
Yes, through integration and unit tests
Yes, but these functions were just introduced (no releases were made yet with these functions)
=> Reorder `validation_history` parameters to be more idiomatic

pyiceberg/catalog/hive.py, tests/catalog/test_hive.py
Let the hive metastore does not compute hive stats which is not used by iceberg.
Details see the java version (https://github.com/apache/iceberg/pull/4407)
Existing tests
No
=> Hive: Add DO_NOT_UPDATE_STATS in alter_table

pyiceberg/table/metadata.py
Closes #1974.
See https://github.com/apache/iceberg-python/issues/1974 description.
N/A.
I don't think we need to consider user-facing changes because it involves V3 which is liable to change.
=> Remove `row-lineage` field in V3 metadata

mkdocs/docs/contributing.md
Closes #1964
Following all steps in the contributing docs leads to error. Running `make install-poetry` should be done before the environment is activated.
Yes
No
=> [Docs] Improve contributing docs

Makefile
Decouple setup and exec in integration tests for better flexibility and isolation.
For example, currently, `make test-integration` must be executed in a physical server.
It is because `docker xxx` cannot be executed within a container (docker in docker is out of scope of this PR). 
Sometimes, it is useful for local debugging, as poetry cannot provide system level isolation, includes environment variables and shared libs.
This PR allows us to run `make test-integration-exec` within a container environment, after we have run `make test-integration-setup` on this server. 
Existing tests.
No.
=> Build: Decouple setup and exec in integration tests for better flexibility

pyiceberg/table/__init__.py, tests/table/test_upsert.py
Previously, the **upsert** functionality was implemented at the **table** level, which meant it always initiated a new **Transaction**. This change moves the **upsert** implementation to the **Transaction** level while keeping `table.upsert(...)` as an entry point. 
With this refactor, end users now have the flexibility to call **upsert** in two ways:
- `table.upsert(...)` – which still starts a new transaction.
- `transaction.upsert(...)` – allowing upserts within an existing transaction.
Using existing tests.
Yes. This change enables users to perform **upserts within an existing transaction** using `transaction.upsert(...)`, in addition to the existing `table.upsert(...)` method.
=> Move implementation of upsert from Table to Transaction

pyiceberg/io/fsspec.py
Currently pyiceberg remote singing only works if the sign endpoint is shared by all tables in a REST Catalog.
However, some Catalogs use table specific endpoints.
If table specific endpoints are used, Pyiceberg sends the sign request for the second table that is queried to the sign endpoint of the first table.
The reason for this is, that although we [re-register() a new signer with different properties](https://github.com/apache/iceberg-python/blob/996a7ba4dbf4afdb3d46689f1715206b1c355f2a/pyiceberg/io/fsspec.py#L166), this statement has no effect the second time it runs because of the unique_id, even if the properties are different.
https://github.com/boto/botocore/blob/8c517320c6a40cd91e8e7fbb05e27183ba2f6dce/botocore/hooks.py#L310-L312
This PR first unregisters the old handler, before …
=> fix: Remote signing with table specific s3.signer.endpoint

tests/integration/test_writes/test_optimistic_concurrency.py, tests/integration/test_writes/test_writes.py
I think it would be great to also have integration tests that make it easy to replicate certain scenarios.
Added some simple ones, but we can extend by having two tables that modify a different partition etc.
=> Add tests for optimistic concurrency

mkdocs/docs/configuration.md, poetry.lock, pyiceberg/io/__init__.py, pyiceberg/io/fsspec.py, pyproject.toml
Add support for the Hugging Face filesystem in `fsspec`, which uses `hf://` paths.
This allows to import [HF datasets](https://huggingface.co/datasets).
Authentication is done using the `"hf.token"` property.
I tried locally but haven't added tests in test_fsspec.py (lmk if it's a requirement)
No changes, it simply adds support for `hf://` URLs
=> Add Hugging Face filesystem support to fsspec

.gitignore
VSCode places all of its files in a folder now. We should add that folder to gitignore in the same way we added the original files.
No tests necessary.
None.
=> Add .vscode folder to .gitignore file

pyiceberg/table/update/validate.py, tests/table/test_validate.py
`validation_history` is a helper function that will be used for checking for newly added manifests. Hence it would make sense to make this function private before it is released.
Yes, integration tests and unit tests.
This function has yet to be released
=> Make `validation_history` private before release

pyiceberg/catalog/dynamodb.py, pyiceberg/catalog/glue.py, pyiceberg/cli/console.py, pyiceberg/schema.py, pyiceberg/utils/config.py
Baby PR to remove `assert` statements out of any non-test code.
=> chore: remove non-test asserts

pyiceberg/manifest.py
Closes https://github.com/apache/iceberg-python/issues/1982
Adds v3 structs for data files, manifest entries, and manifest lists. Necessary for related v3 work.
No, these are just schemas.
No
=> Add v3 structs

pyiceberg/catalog/rest/__init__.py, tests/catalog/test_rest.py
Let `requests` handle dealing with params instead of using `.format` on a templated string.
=> maint: let requests handle params formatting

.pre-commit-config.yaml, pyiceberg/expressions/literals.py, pyiceberg/io/fsspec.py, pyiceberg/manifest.py, pyiceberg/transforms.py
=> Bump mypy in pre-commit

pyiceberg/catalog/__init__.py, pyiceberg/utils/config.py, tests/utils/test_config.py
Adds a new function `pyiceberg.catalog.list_catalogs() -> List[str]` to list all known catalogs.
In creating a pyiceberg-backed API, one must either duplicate the config-parsing logic or access private data in order to know what catalogs are available in the env. I believe that this logic should be part of the library. 
Yes
Yes, knew public function in `pyiceberg.catalog`
=> feat: support listing known catalogs

dev/Dockerfile
=> Bump Iceberg-Java to 1.9.1

pyiceberg/catalog/__init__.py, pyiceberg/catalog/hive.py, pyiceberg/catalog/memory.py, pyiceberg/catalog/sql.py, pyiceberg/cli/console.py, pyiceberg/io/fsspec.py
Noticed a few more places we can be using the constant instead of the string!
=> maint: use `URI` constant instead of 'uri' strings

poetry.lock
In https://github.com/apache/iceberg-python/pull/2125 we got a warning from the google-auth package, and we're on `1.6.3` while `2.40.3` is out there. So maybe good to bump everything 👍
=> Build: Bump third party deps

pyiceberg/avro/codecs/zstandard_codec.py, tests/utils/test_manifest.py
The return type of the decompress method in `ZStandardCodec` should be `bytes`, but it currently returns a `bytearray`, which causes an exception when reading Avro files compressed with zstd.
```text
def new_decoder(b: bytes) -> BinaryDecoder:
try:
from pyiceberg.avro.decoder_fast import CythonBinaryDecoder
>           return CythonBinaryDecoder(b)
E           TypeError: Argument 'input_contents' has incorrect type (expected bytes, got bytearray)
```
Yes,  `test_write_manifest`
No.
=> fix: correct type mismatch in avro zstd decompression.

.github/workflows/python-ci.yml, Makefile, pyproject.toml
Closes #2124
Refactor `Makefile` 
* Grouped commands and added comments
* Added `COVERAGE` param to run test with coverage
* Added `COVERAGE_FAIL_UNDER` param to specify coverage threshold to pass
* Change test coverage threshold to `85` for unit tests, we are currently at `87`
* Change test coverage threshold to `75` for integration tests, we are currently at `77`
CI 
* Add s3/adls/gcs integration tests to run in CI
* Run tests with coverage report
Note the `gcsfs` issue was resolved by #2127
Yes
No
=> Refactor `Makefile` and run s3/adls/gcs integration tests in CI

pyiceberg/table/__init__.py, pyiceberg/table/inspect.py
Should help with #2130 and #2132
Modifies `Table.add_files` to explicitly use `inspect.data_files` and also parallelize `inspect._files`
I didn't see anywhere else where looping over manifest entries was parallelized, so seems better to parallelize across manifests than within.
No changes here but should be faster.
=> perf: optimize `table.add_files` and `inspect.files`

dev/provision.py, tests/integration/test_writes/test_writes.py
=> Run `test_create_table_transaction` for Rest V1 tables

mkdocs/docs/configuration.md
Missing parameter in REST Catalog documentation
Doc only
Doc only
=> Add warehouse parameter to the REST Catalog doc

poetry.lock
Manually update `multidict` dependency
Running `make install` gave the following warning:
```
Warning: The file chosen for install of multidict 6.5.0 (multidict-6.5.0-cp312-cp312-macosx_11_0_arm64.whl) is yanked. Reason for being yanked: The version has a regression in 'md.update()' in certain conditions
```
=> dep: update `multidict`, previous version yanked

pyiceberg/catalog/glue.py, tests/catalog/test_glue.py
See https://github.com/apache/iceberg-python/pull/2013
Closes https://github.com/apache/iceberg-python/issues/2064
Continuing the trend, but with glue.
See test below
When a user specifies property update on commit table, those parameters will be passed to the glue client.
=> fix: add metadata_properties to _construct_parameters when updating glue table

mkdocs/docs/SUMMARY.md, mkdocs/docs/expression-dsl.md, mkdocs/docs/row-filter-syntax.md
scan's `row_filter` param is not super intuitive. I got tired of reading over the expression and parser code as I'm trying to build out statements, so I had some docs made up.  
They are docs only, so not really? 
Yes there are docs for the expression and string syntaxes of `row_filter` now.
=> Documented `row_filter` expressions

mkdocs/docs/api.md, poetry.lock, pyiceberg/table/__init__.py, pyproject.toml, tests/table/test_datafusion.py
- Added pyiceberg table integration so that pyiceberg `Table` can be pass in directly to datafusion's `register_table_provider` 
- Added `datafusion` as a optional dependency
- Added docs for the integration:
Yes
=> add iceberg datafusion integration

mkdocs/docs/cli.md, pyiceberg/cli/console.py, tests/cli/test_console.py
Hello!
Setting or removing table properties on console currently raise a `Writing is WIP` error. This PR adds the code to set and remove table properties.
Yes
Yes, setting and removing table properties on console now works.
=> feat: add support for setting and removing table properties on console

dev/Dockerfile
Adding `pyiceberg["pyarrow"]` dep to the Dockefile resolves these warning log lines:
```
Could not initialize FileIO: pyiceberg.io.pyarrow.PyArrowFileIO
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/pyiceberg/io/__init__.py", line 317, in _import_file_io
module = importlib.import_module(module_name)
File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
File "<frozen importlib._bootstrap_external>", …
```
=> dev integration: add pyiceberg[pyarrow] to Dockerfile to resolve missing pyarrow import error

mkdocs/docs/configuration.md
Closes #2096
Included examples and detailed configuration guidance to enhance clarity.
=> Improve Docs for IRC Catalog Connection

pyiceberg/table/__init__.py
Silence PyCharm warning that `DataScan::_check_sequence_number` can be static.
N/A
No
=> Nit: Make `DataScan::_check_sequence_number` static

pyiceberg/utils/schema_conversion.py, tests/utils/test_schema_conversion.py
The schema conversion util from avro schema to iceberg schema did ignore `timestamp-millis`. 
Also added conversion from `uuid` 
Added tests for `timestamp-millis` and `timestamp-micros` as the latter was missing
no
=> feat: add schema conversion from avro `timestamp-millis` and `uuid`

pyiceberg/table/statistics.py, pyiceberg/table/update/__init__.py, tests/table/test_init.py
Closes #2191 
apache/iceberg supports these two event types. We should do the same to match the Java implementation and allow users to alter their partition statistics files.
[REST Spec Reference]([apache/iceberg@09140e5/open-api/rest-catalog-open-api.yaml#L2981-L3004](https://github.com/apache/iceberg/blob/09140e52836048b112c42c9cfe721295bd57048b/open-api/rest-catalog-open-api.yaml#L2981-L3004))
Unit test included.
- Adds `RemovePartitionStatisticsUpdate` and `SetPartitionStatisticsUpdate` actions.
=> Add RemovePartitionStatisticsUpdate and SetPartitionStatisticsUpdate

pyiceberg/table/snapshots.py, tests/table/test_snapshots.py
Adding the snapshot property to keep parity with [Java](https://github.com/apache/iceberg/commits/main/core/src/main/java/org/apache/iceberg/SnapshotSummary.java)
Yes I modified two of the existing tests to add this property and added an additional two for cases where the table is unchanged or unpartitioned.
Yes, this will add a property to the Snapshot Summaries when partitions are changed.
=> add PARTITION_SUMMARY_PROP

pyiceberg/transforms.py, tests/test_transforms.py
Added a NotInstalledException check when pyiceberg_core is imported for pyarrow_transforms This will raise a helpful error message when endusers try to use methods that depend on pyiceberg_core but haven't installed the optional dependency
Closes #1987 
If an enduser hasn't installed the `pyiceberg_core` optional dependency, using pyarrow transforms will crash with an unhelpful error. This PR gives the enduser a nicer error message that informs them to install the optional dependency
Yes, a test was added to verify the behaviour
=> Add import check for optional dependency on pyiceberg_core

pyiceberg/io/pyarrow.py, tests/io/test_pyarrow.py
Closes #2017
Include the column name in the error message to make it more descriptive.
=> Add Column Name to the Error Message in StatsAggregator

pyiceberg/utils/schema_conversion.py, tests/utils/test_schema_conversion.py
Follow up to #2173, the conversion as implemented is not safe since iceberg does not natively have `millis` precision. Timestamp values are implicitly in `micros` precision
This is confirmed by https://github.com/apache/iceberg-python/pull/2173#discussion_r2209756001
Let's revert for now and follow up to figure out the right way to support `millis` precision.
=> revert avro timestamp-millis mapping

mkdocs/docs/community.md
Closes #2238 
The pyiceberg monthly sync is now a part of the Iceberg Dev Events calendar. 
Just docs
=> [docs] Include link to Iceberg Dev Events in docs

pyiceberg/avro/codecs/snappy_codec.py
The `SnappyCodec.decompress()` method has a bug where the CRC32 checksum is extracted from the compressed data **after** the data has already been truncated to remove the checksum. This results in reading the wrong 4 bytes for checksum validation, causing the CRC32 check to fail incorrectly.
**Root Cause:**
In the current implementation:
1. `data = data[0:-4]` removes the last 4 bytes (checksum) from the data
2. `checksum = data[-4:]` then tries to get the checksum from the already-truncated data  
3. This means `checksum` contains the wrong bytes (last 4 bytes of compressed data instead of the actual checksum)
**Solution:**
Extract the checksum **before** truncating the data:
```python
checksum = data[-4:]  # store checksum before truncating data
data = data[0:-4]     # remove checksum …
```
=> BUG: Snappy checksum check

dev/docker-compose-azurite.yml, poetry.lock, pyproject.toml
As title. Closes #2258. Updated the lockfile just in case but it didn't change the Arrow version.
PyIceberg doesn't need this upper bound since it uses stable public APIs of PyArrow (as far as I can tell).
Dependency version upper bounds are known to be problematic:
1. Cause cascading dependency conflicts
2. Block security and bug fixes
3. Limit user flexibility
In my case, this causes issues for Bodo's Arrow upgrades since both Arrow and PyIceberg are dependencies.
Existing tests.
None except allowing newer PyArrow versions.
=> Remove PyArrow version upper bound and update lockfile

.github/workflows/python-ci.yml
Looks like something changed, which caused the CI to fail: https://github.com/apache/iceberg-python/commits/main/
First attempt to isolate the issue (checking if it is related to coverage)
=> CI: Disable caching

pyiceberg/io/pyarrow.py
I noticed we just passed in the value, without setting the type explicitly. By default, PyArrow will for example upscale 1 to an int64 field, while the column is of type int32 in the table.
=> Pass in type explicitly for `initial-default`

pyiceberg/types.py, tests/test_types.py
Closes #1853 
This adds a new repr function that ensures that `initial-default` and `write-default` will not appear if they are None. Unfortunately, this functionality isn't baked into Pydantic.
__repr__ changes may be breaking.
Tests included.
=> Change __repr__ method to only print if non-None

.github/workflows/check-md-link.yml
https://github.com/gaurav-nelson/github-action-markdown-link-check has been deprecated since Apr 2025 and https://github.com/tcort/github-action-markdown-link-check is recommended.
GH action change.
No.
=> Build: Migrate markdown-link-check GH action

pyiceberg/table/__init__.py, pyiceberg/table/update/__init__.py, pyiceberg/table/update/schema.py, tests/catalog/test_base.py, tests/catalog/test_rest.py
[AddSchemaUpdate openapi spec](https://github.com/apache/iceberg/blob/6017fec2b67884424f152e497424e48414c4a4f3/open-api/rest-catalog-open-api.yaml#L2759-L2767)
=> remove deprecated code for 0.10 release

pyiceberg/io/pyarrow.py, tests/io/test_pyarrow.py
This PR fix reading pyarrow timestamp as Iceberg timestamptz type. It mirrors the pyarrow logic for dealing with pyarrow timestamp types [here](https://github.com/apache/iceberg-python/blob/8b43eb88fcc80b4980ce16b71852d211d7e93b13/pyiceberg/io/pyarrow.py#L1330-L1353)
Two changes were made to `ArrowProjectionVisitor._cast_if_needed`
1. reorder the logic so that we handle dealing with timestamp first. Otherwise, it will try to `promote()` timestamp to timestamptz and fail.
2. allow casting when the pyarrow's value has `None` timezone. This is allowed because we gate on the target type has "UTC" timezone. It mirrors the java logic for reading with default UTC timezone ([1](https://github.com/apache/iceberg/blob/856cbf6eb8a85dee01c65ae6291274b700f76746/core/src/main/java/org/apache/iceberg/dat …
=> fix: allow reading pyarrow timestamp as iceberg timestamptz

.pre-commit-config.yaml
issue #2341 
In this PR i update only `pre-commit-hooks` (updating `v5.0.0 -> v6.0.0`) in `.pre-commit-config.yaml` file.
i tested it with 'make lint' command and it  looks good to me.
=> Bump `pre-commit-hooks` in `.pre-commit-config.yaml` file

.pre-commit-config.yaml
issue #2341 
In this PR I update `mirrors-mypy` (from `v1.16.0 -> v1.17.1`) in `.pre-commit-config.yaml` file.
After the update, I ran make lint, and it executed successfully without any issues.
=> Bump `mirrors-mypy` in `.pre-commit-config.yaml` file

pyiceberg/table/inspect.py
Parallelizes manifest processing to improve performance for large tables with many manifest files. After parallel processing, merges the resulting partition maps to produce the final aggregated result.
Previous example ref: e937f6a1811c9e090552a4ae2015a8032e7ea910
Perf improvement.
We experienced slowness with table.inspect.partitions() with large table.
Yes.
No.
=> perf: optimize `inspect.partitions`

.github/pull_request_template.md, .pre-commit-config.yaml, README.md, mkdocs/docs/how-to-release.md, mkdocs/docs/verify-release.md
issue #2341 
Initially, I updated `markdownlint-cli` from `v0.43.0 → v0.45.0`, but running `make lint` failed with errors:
After that, I downgraded slightly to `v0.44.0` (instead of `v0.45.0`), and `make lint` executed successfully:
=> Bump `markdownlint-cli` in `.pre-commit-config.yaml` file

.pre-commit-config.yaml
issue #2341 
In this PR, I update `flynt` (from`1.0.1 -> 1.0.6`) in `.pre-commit-comfig.yaml` file.
Testing:
=> Bump `flynt` in `.pre-commit-config.yaml` file

.pre-commit-config.yaml
Remove this since its unused. we cannot use pre-commit ci since it requires "write access to code" permission
https://github.com/apache/iceberg-python/issues/2378#issuecomment-3217100343
=> infra: remove precommit ci

pyiceberg/table/update/__init__.py, tests/test_serializers.py
Closes #2342
The last attempt at fixing this (#2343) did not actually end up serializing None values to `null`. This was b/c the `AssertRefSnapshotId` requirement was often a child object of some other `Request` object, which was actually getting the  `model_dump_json()` call. This meant that the `exclude_none=True` override would remove any `None`s _before_ any of the `Field`-specific configurations would be considered (like `exclude=False` or the model's own `model_dump_json` method).
I then investigated setting some `ConfigDict` settings on the model, but that also did not have any useful configurations.
I looked into setting `exclude_none=True` at all of the `model_json_dump()` callsites but there were too many and it would be easy to forget to set that value every time. The issue is …
=> Add serializer for AssertRefSnapshotId allowing null json value

mkdocs/docs/contributing.md
Heading levels of subsections of `Code standards` are incorrect such that subsection headings are rendered on the same level as `Code standards`.
Doc changes only.
=> Fix heading levels of subsections of Code standards

pyiceberg/catalog/__init__.py, pyiceberg/catalog/sql.py, tests/catalog/test_base.py, tests/catalog/test_sql.py
Closes #2346 
Add option to close catalog
Yes
Yes
=> Add close option

pyiceberg/io/__init__.py
Now that [pyarrow FileIO supports ADLS](https://github.com/apache/iceberg-python/pull/2111), we can update the [SCHEMA_TO_FILE_IO](https://github.com/apache/iceberg-python/blob/370e770383c9c129aff2fe24cc92a68981688159/pyiceberg/io/__init__.py#L307-L319) mapping for `abfs` and `wasb` to use ARROW_FILE_IO, similar to how it’s handled for s3
We’re keeping FsspecFileIO as the preferred default, since the PyArrowFileIO implementation is only available in pyarrow >= 20.0.0
Add mapping SCHEMA_TO_FILE_IO for `wasb` and `abfs` to `FsspecFileIO` and `PyArrowFileIO`
=> use PyArrowFileIO as default for abfs and wasb schemes

pyiceberg/io/fsspec.py, tests/io/test_fsspec.py
`s3fs.S3FileSystem` requires that we pass `anon` directly, it cannot be passed through `config_kwargs`.
yes, unit tests updated.
no
=> use anon argument when configuring s3fs.S3FileSystem

tests/catalog/test_rest.py
Request sessions could load `REQUESTS_CA_BUNDLE` or `CURL_CA_BUNDLE` from OS environment such that cabundle passed in from the UT is not used.
https://github.com/psf/requests/blob/88dce9d854797c05d0ff296b70e0430535ef8aaf/src/requests/sessions.py#L766-L771
Yes
No
=> Fix rest test with ssl_ca_bundle due to conflicts with OS environment

pyiceberg/catalog/rest/__init__.py, tests/catalog/test_rest.py
Part of #2399 
This PR introducs the implementation of  `close()` method to the `RestCatalog`. 
And add corresponding test case which following the test pattern in #2390
Yes
=> Add `close()` method to RestCatalog

pyproject.toml
This PR explicitly add `poetry.lock` to the source distribution artifact so that we can build and test RCs with pinned dependencies.
We want to pin dependencies because we verify a release candidate (RC) by re-building the project from source distribution. We [unzip the artifact](https://py.iceberg.apache.org/verify-release/#verifying-license-documentation), [install the dependencies with `make install`, and then run tests](https://py.iceberg.apache.org/verify-release/#testing). 
Since `poetry.lock` is not automatically added to the source distribution, `make install` will install packages only based on `pyproject.toml`. The resolver will pull in the latest version by default, which can lead to compatibility issues. 
For example, in 0.10 RC2, we see that this pulled in the latest …
=> build: add poetry.lock to sdist

pyiceberg/manifest.py, tests/catalog/test_sql.py
A faulty refactor:
https://github.com/apache/iceberg-python/commit/59742e01e8d190aa759e0154b03300bd81a28d02#diff-e9df836e263024ba54e2706853fb25c00269fbfe3726b440ba57f4a929c995dcR927
This produces incorrect metadata, but was hidden by the writer.
=> Set the ManifestEntryStatus

Makefile
related to #2425
Removing the user flag from the poetry installation to allow users who want to install poetry into a separate dedicated virtual environment.
This virtual environment must be separate from the environment in which we install the iceberg-python repo. 
Yes manual testing 
```
> python3 -m venv ~/.venvs/poetry
> source ~/.venvs/poetry/bin/activate
>  echo $VIRTUAL_ENV
/Users/geru/.venvs/poetry
> python -m pip install -U pip setuptools wheel
> poetry --version
Poetry (version 2.1.4)
> poetry show -v
Using virtualenv: /Users/geru/workspace/iceberg-python/.venv
> poetry install
SUCCESS
```
no
cc: @kevinjqliu
=> Remove user flag from poetry installation

dev/Dockerfile
This PR changes the Dockerfile url to use `downloads.apache.org/spark` first and then fallbacks to `https://archive.apache.org/dist`. 
This should give us speed and reliability. 
`https://archive.apache.org/dist` is very slow, we switch to it because its more reliable and contains all versions of Spark. 
`downloads.apache.org/spark` hosts the latest versions of spark, its typically faster. 
Thanks @mccormickt12 for the great idea!
yes
```
make test-integration-rebuild && make test-integration
```
also tested fallback logic
=> infra: prefer downloads.apache.org, fallback to archive.apache.org

pyiceberg/table/update/spec.py
When doing a commit that evolves the partition spec we are missing a requirement for asserting that the base default spec id has not changed. 
This change comes from reviewing #2479 which adds catalog tests to test the behavior of spec evolutions, specifically, one of the tests that commits a spec update conflict fails since does not raise `CommitFailedException`
No.
=> BUG: Add assert spec id to requirements in spec update

pyiceberg/io/fsspec.py, tests/io/test_fsspec.py
`FsspecFileIO.get_fs` can be called by multiple threads when `ExecutorFactory` is used (for example by `DataScan.plan_files`).
The base class of `fsspec` filesystem objects, `fsspec.spec.AbstractFileSystem`, internally caches instances through the `fsspec.spec._Cached` metaclass. The caching key used includes `threading.get_ident()`, making entries thread-local:
https://github.com/fsspec/filesystem_spec/blob/f84b99f0d1f079f990db1a219b74df66ab3e7160/fsspec/spec.py#L71
The `FsspecFileIO.get_fs` LRU cache (around `FsspecFileIO._get_fs`) breaks the thread-locality of the filesystem instances as it will return the same instance for different threads.
One consequence of this is that for `s3fs.S3FileSystem`, HTTP connection pooling no longer occurs per thread (as is normal with `aiobotocore`), …
=> Fix `FsspecFileIO.get_fs` thread safety

tests/avro/test_reader.py, tests/conftest.py
Follow-up of https://github.com/apache/iceberg-python/pull/2265 where some partition fields were renamed to avoid naming conflicts but the fixtures were not updated properly.
=> Fix renames of `tpep_pickup_datetime` → `tpep_pickup_day`

mkdocs/docs/contributing.md, tests/integration/test_catalog.py
Closes #2481 
This allows users to run our test suite against their REST Catalog implementations. 
Test-only change
- Adds support for running catalog tests against REST Catalog implementations.
=> Run Catalog integration tests against REST Catalog impls

pyiceberg/table/update/__init__.py, tests/table/test_init.py
This adds RemovePartitionSpecsUpdate, another missing TableMetadata update event.
It also ends up testing AddPartitionSpecUpdate, which it looks like it untested.
[REST API Spec Reference](https://github.com/apache/iceberg/blob/09140e52836048b112c42c9cfe721295bd57048b/open-api/rest-catalog-open-api.yaml#L3006-L3018)
Unit tests added.
- Added RemovePartitionSpecsUpdate event
=> Add RemovePartitionSpecsUpdate event

pyiceberg/manifest.py
=> add lock for cachetools

pyproject.toml
Closes #1349
After we upgrade to use spark 4.x in #2566, we can remove these filterwarnings
=> infra: remove outdated filterwarnings

pyiceberg/utils/concurrent.py, tests/utils/test_concurrent.py
`ExecutorFactor` can be left in an invalid state, which causes new `submit` calls to hang indefinitely in multiprocessing.  
Closes https://github.com/apache/iceberg-python/issues/2545
This PR detects when the executor is used in a new process and creates a new instance
Yes, new tests added to `test_concurrent.py`
No
=> Make `ExecutorFactory` multi-process safe

mkdocs/docs/api.md
Improved docs for tagging and branching to explicitly show how to create and delete branches/tags along with their props
No code changes.
No
=> DOCS: Add better docs for tags and branches

poetry.lock, pyproject.toml, tests/io/test_pyarrow.py
We don't support `<3.9`, so lets get rid of complexity
=> Simplify ray contraint

poetry.lock, pyproject.toml
Closes #2590 
I seem to be faster than the dependabot : ). 
Pin pydantic version to `<2.12.0` to avoid the recent regression: https://github.com/pydantic/pydantic/issues/12347.
I made this an upper bound because it is unclear about the fix plan in pydantic community. Once their fix is out, we could release the upper bound and exclude affected versions only
No dependency version update. Tested the new version in https://github.com/apache/iceberg-python/pull/2589 and confirmed the regression
No
cc: @Fokko @kevinjqliu
=> [Upstream Error] Pin pydantic version <2.12.0 to avoid regression
