apache/iceberg-python

.asf.yaml
This keeps the git history clear
=> Disable merge-commit and enforce linear history

pyiceberg/io/pyarrow.py
Should be `FIXED_LEN_BYTE_ARRAY`
=> Fix Arrow fixed type

tests/table/test_init.py
After merging #127, it looks like another PR merged today needs to be formatted by the new linter.
=> Fix lint tests failed in main

poetry.lock, pyproject.toml
There seem to be some issues with the later version: https://github.com/apache/iceberg-python/pull/287
=> Lock Ray on <2.8.0

pyiceberg/table/__init__.py, tests/integration/test_writes.py
Annotations are not checked at runtime
=> Check the types when writing

tests/conftest.py
Otherwise we need to have this installed for the tests of the Avro Decoder: https://github.com/apache/iceberg-python/actions/runs/7717163089
=> Remove `MotoServer` from the `conftest.py` scope

pyiceberg/io/pyarrow.py
Noticed this while debugging some stuff.
=> Small simplification in the name-mapping

mkdocs/docs/index.md
Related to #326 [Add example of using PyIceberg with minimal external dependencies]
=> Get Started: Add sqlcatalog and local fs warehouse

poetry.lock, pyproject.toml, tests/catalog/test_dynamodb.py, tests/catalog/test_glue.py, tests/conftest.py
=> Build: Bump moto from 4.2.13 to 5.0.1

pyiceberg/io/pyarrow.py, tests/integration/test_writes.py
=> Do not set Parquet version

.github/workflows/python-release.yml
Same as in https://github.com/apache/iceberg-python/pull/373
=> release: Bump the moto version

tests/catalog/test_sql.py, tests/conftest.py, tests/integration/test_writes.py
=> Add test to capture Duckdb behavior

.pre-commit-config.yaml, pyiceberg/avro/decoder_fast.pyi, pyiceberg/avro/decoder_fast.pyx, pyiceberg/catalog/rest.py, pyiceberg/conversions.py, pyiceberg/table/__init__.py, pyproject.toml, tests/avro/test_decoder.py
I wasn't able to bump Ruff yet due to an issue: https://github.com/astral-sh/ruff/issues/10034
=> Bump pre-commit and such

tests/integration/test_writes.py
=> Remove extraneous import

tests/conftest.py
Fixes #492
Thanks @HonahX for the provided solution :)
=> Default spark session timezone to UTC in test

mkdocs/docs/configuration.md
docs update related to #484 @Fokko
=> add rest scope in the config documentation

mkdocs/docs/configuration.md, pyiceberg/serializers.py, pyiceberg/table/metadata.py, pyiceberg/utils/concurrent.py, pyiceberg/utils/config.py, tests/test_serializers.py, tests/utils/test_config.py
=> [0.6.x] Backport #473 for current-snapshot-id backwards compatibility

pyiceberg/catalog/glue.py, pyiceberg/catalog/hive.py, pyiceberg/catalog/noop.py, pyiceberg/catalog/rest.py, pyiceberg/catalog/sql.py, pyiceberg/expressions/visitors.py, pyiceberg/io/pyarrow.py, pyiceberg/table/__init__.py, tests/catalog/test_base.py, tests/catalog/test_rest.py, tests/catalog/test_sql.py, tests/expressions/test_parser.py, tests/integration/test_writes.py, tests/io/test_pyarrow.py, tests/table/test_init.py, tests/table/test_metadata.py, tests/test_schema.py, tests/utils/test_manifest.py
=> [0.6.x] Backport #505 to correct imports

pyiceberg/io/pyarrow.py, pyiceberg/schema.py, pyiceberg/table/__init__.py, pyiceberg/table/name_mapping.py, tests/table/test_init.py
=> [0.6.x] Backport PR #352 to Improve error message in case of a mismatch

pyiceberg/table/__init__.py
=> Call as_arrow() call in `overwrite`

pyiceberg/table/__init__.py, tests/integration/test_reads.py, tests/integration/test_writes.py
=> [0.6.x] Backport #563 for minor fixes

pyiceberg/table/__init__.py
I think this is more verbose than required.
=> Remove `as visitors` import

.github/workflows/python-integration.yml, Makefile, dev/run-azurite.sh, dev/run-gcs-server.sh, dev/run-minio.sh
=> [CI FIx] Use Docker Compose V2

pyiceberg/expressions/literals.py, pyiceberg/io/pyarrow.py, tests/conftest.py, tests/expressions/test_literals.py, tests/integration/test_writes.py, tests/io/test_pyarrow.py
=> [0.6.x] Backport #529 and #597

poetry.lock, pyiceberg/catalog/hive.py
Backport #607 and #434
No merge conflict, just open a PR for CI to run
Bump getdaft to 0.2.15 since there is some installation issue with 0.2.14 in github action
=> [0.6.x] Backport #607 and #434

pyproject.toml
=> [0.6.x] Backport #615

pyiceberg/catalog/rest.py
=> Remove NoSuchNamespaceError on namespace creation

pyiceberg/io/__init__.py, pyiceberg/io/pyarrow.py
- Add support for metadata point to `viewfs` path in Hadoop/HDFS environment
=> feat: Support viewfs scheme along side with hdfs

tests/integration/test_writes/test_partitioned_writes.py
=> Don't refresh table in the for-loop

pyiceberg/catalog/rest.py
=> Fix pydantic warning in the commit process

pyiceberg/catalog/__init__.py, pyiceberg/catalog/sql.py
resolves: #1163 (again)
two more docstrings that are no longer relevant
=> follow up for more cleanup

pyiceberg/table/snapshots.py, tests/table/test_snapshots.py
And then default to `overwrite`, see:
https://lists.apache.org/thread/h9qmrmlgxh91ol0y2v8olt90b9q6p9xr
=> Allow for missing operation

.pre-commit-config.yaml, pyiceberg/catalog/dynamodb.py, pyiceberg/catalog/glue.py, pyiceberg/io/pyarrow.py, pyiceberg/table/update/schema.py, pyiceberg/typedef.py, pyiceberg/utils/schema_conversion.py, tests/avro/test_file.py, tests/avro/test_writer.py, tests/catalog/test_base.py, tests/catalog/test_rest.py, tests/expressions/test_visitors.py, tests/integration/test_writes/test_writes.py, tests/table/test_init.py, tests/test_transforms.py
=> Bump `pre-commit` versions

mkdocs/docs/api.md
It's code an example be wrong.
=> docs: fixed code example.

pyiceberg/io/fsspec.py
Similar to Java:
https://github.com/apache/iceberg/blob/91a1505d09cebcd1d088ac53cd42732c343883de/aws/src/main/java/org/apache/iceberg/aws/s3/signer/S3V4RestSignerClient.java#L205
Fixes #1442
=> Signer: Make token optional

pyiceberg/__init__.py, pyproject.toml
Bump version to `0.9.0` to prepare for the next release
=> bump version to 0.9.0

pyiceberg/manifest.py
This reverts commit 4e755996c11e1768a63d3f3f663bfa77994648b7 which causes a sad CI
=> Revert "Add support for lowercase `FileFormat`(#1362)"

pyiceberg/transforms.py
Similar to https://github.com/apache/iceberg-python/pull/1562
=> Refactor `{year,month,day,hour}` transform

mkdocs/docs/api.md, pyiceberg/table/__init__.py, pyiceberg/table/update/statistics.py
@Fokko I forgot to update the statistics documentation in the previous PR.
=> Fix statistics documentation by removing snapshot_id references

pyiceberg/table/__init__.py, pyiceberg/table/upsert_util.py, tests/table/test_upsert.py
Also slight refactor of the tests to bring it more in line with the rest
=> Upsert: Reuse existing expression to detect rows to be inserted

mkdocs/docs/contributing.md
More context [here](https://github.com/apache/iceberg-python/pull/1673) 
Wanted to keep it as short as possible
@kevinjqliu
=> Add instruction to install shell plugin to doc

.github/ISSUE_TEMPLATE/iceberg_bug_report.yml, dev/Dockerfile
https://github.com/apache/iceberg-python/blob/main/mkdocs/docs/how-to-release.md#update-the-github-template
1. Update the Github template
2. Update the integration tests
=> 0.9.0 post release

pyiceberg/io/pyarrow.py
Potential fix for https://github.com/apache/iceberg-python/issues/1804
Might want to write a test, but not sure yet how to reproduce without using glue.
Closes https://github.com/apache/iceberg-python/issues/1804
=> Temporary fix for Arrow issue 46057

dev/Dockerfile
=> Bump Snapshot versions

pyiceberg/__init__.py, pyproject.toml
=> Bump to 0.9.1

dev/Dockerfile, tests/conftest.py
Tests against the latest release of Iceberg that has Deletion Vectors 👍
=> CI: Bump to Iceberg 1.9.0

tests/conftest.py
The [integration tests started failing](https://github.com/apache/iceberg-python/commits/main/); this fixes it, according to Stack Overflow and the CI.
=> Try setting the IP for the integration tests

.pre-commit-config.yaml, tests/catalog/test_rest.py, tests/expressions/test_visitors.py, tests/table/test_init.py, tests/table/test_upsert.py, tests/test_types.py, tests/utils/test_manifest.py
=> Bump Ruff to the latest version

dev/Dockerfile
=> Bump PyIceberg to 0.9.1

dev/Dockerfile
=> Bump tests to Spark 3.5.6

tests/conftest.py
Just a small bump, noticed this while working on some other stuff
=> Bump Iceberg in CI

Makefile
=> Bump Poetry to 2.1.4

.github/workflows/python-ci-docs.yml, .github/workflows/python-ci.yml, .github/workflows/python-release-docs.yml, Makefile
On Windows, `poetry` is not automatically put in the PATH
`pip` also might point to a different executable 
Source all commands from the same `python`
=> infra: let Makefile execute command from python

Makefile
```bash
make test
```
Successfully runs.
None.
For maintainers, upgrade using:
```bash
make install-poetry
```
=> Upgrade poetry to latest (2.2.1)
